import fetcher

animals = [
    {'level': 1, 'name': 'Monkey', 'options': ['Donkey', 'Koala', 'Pig', 'Gorilla', 'Hamster', 'Porcupine', 'Bear']},
    {'level': 1, 'name': 'Buffalo', 'options': ['Elephant', 'Camel', 'Goat', 'Zebra', 'Cow', 'Donkey', 'Horse']},
    {'level': 1, 'name': 'Camel', 'options': ['Elephant', 'Dog', 'Giraffe', 'Pig', 'Baboon', 'Ape']},
    {'level': 1, 'name': 'Cat', 'options': ['Ape', 'Panther', 'Lion', 'Tiger', 'Cheetah', 'Dog']},
    {'level': 1, 'name': 'Dog', 'options': ['Rat', 'Bear', 'Impala', 'Goat', 'Walrus', 'Fox']},
    {'level': 1, 'name': 'Tiger', 'options': ['Lion', 'Fox', 'Puma', 'Jaguar', 'Leopard', 'Deer']},
    {'level': 1, 'name': 'Lion', 'options': ['Tiger', 'Cow', 'Bear', 'Crocodile', 'Cockroach', 'Snail']},
    {'level': 1, 'name': 'Elephant', 'options': ['Sheep', 'Lion', 'Crocodile', 'Crocodile', 'Panda', 'Jaguar']},
    {'level': 1, 'name': 'Giraffe', 'options': ['Cow', 'Horse', 'Rat', 'Squirrel', 'Snail', 'Bobcat']},
    {'level': 1, 'name': 'Zebra', 'options': ['Dog', 'Lion', 'Kangaroo', 'Squirrel', 'Bobcat', 'Jellyfish']},
    {'level': 1, 'name': 'Sheep', 'options': ['Dolphin', 'Cat', 'Hippopotamus', 'Hippopotamus', 'Hyena', 'Gorilla']},
    {'level': 1, 'name': 'Dolphin', 'options': ['Sheep', 'Sheep', 'Hippopotamus', 'Crab', 'Puma', 'Panda']},
    {'level': 1, 'name': 'Cow', 'options': ['Giraffe', 'Elephant', 'Hippopotamus', 'Donkey', 'Hyena', 'Polar Bear']},
    {'level': 1, 'name': 'Horse', 'options': ['Lion', 'Dog', 'Snake', 'Rabbit', 'Bobcat', 'Panda']},
    {'level': 1, 'name': 'Frog', 'options': ['Elephant', 'Cat', 'Pig', 'Bear', 'Chimpanzee', 'Bobcat']},
    {'level': 2, 'name': 'Donkey', 'options': ['Buffalo', 'Zebra', 'Goat', 'Snake', 'Ant', 'Puma']},
    {'level': 2, 'name': 'Crab', 'options': ['Buffalo', 'Monkey', 'Koala', 'Koala', 'Jellyfish', 'Gorilla']},
    {'level': 2, 'name': 'Bear', 'options': ['Zebra', 'Zebra', 'Rhinocerous', 'Fox', 'Cockroach', 'Polar Bear']},
    {'level': 2, 'name': 'Hippopotamus', 'options': ['Giraffe', 'Lion', 'Koala', 'Deer', 'Polar Bear', 'Chimpanzee']},
    {'level': 2, 'name': 'Rhinocerous', 'options': ['Frog', 'Elephant', 'Squirrel', 'Koala', 'Hyena', 'Ant']},
    {'level': 2, 'name': 'Koala', 'options': ['Frog', 'Tiger', 'Crocodile', 'Rabbit', 'Chimpanzee', 'Jaguar']},
    {'level': 2, 'name': 'Kangaroo', 'options': ['Cow', 'Buffalo', 'Rabbit', 'Koala', 'Bobcat', 'Jaguar']},
    {'level': 2, 'name': 'Bull', 'options': ['Sheep', 'Horse', 'Crab', 'Bear', 'Jellyfish', 'Gorilla']},
    {'level': 2, 'name': 'Spider', 'options': ['Buffalo', 'Buffalo', 'Koala', 'Hippopotamus', 'Ape', 'Bobcat']},
    {'level': 2, 'name': 'Pig', 'options': ['Tiger', 'Buffalo', 'Bull', 'Goat', 'Hyena', 'Octopus']},
    {'level': 2, 'name': 'Crocodile', 'options': ['Zebra', 'Camel', 'Rhinocerous', 'Fox', 'Hyena', 'Leopard']},
    {'level': 2, 'name': 'Goat', 'options': ['Cat', 'Tiger', 'Rhinocerous', 'Squirrel', 'Starfish', 'Bobcat']},
    {'level': 2, 'name': 'Rabbit', 'options': ['Monkey', 'Buffalo', 'Kangaroo', 'Hippopotamus', 'Octopus', 'Jaguar']},
    {'level': 2, 'name': 'Fox', 'options': ['Dolphin', 'Elephant', 'Rat', 'Bear', 'Jellyfish', 'Leopard']},
    {'level': 2, 'name': 'Deer', 'options': ['Sheep', 'Buffalo', 'Bear', 'Rat', 'Ant', 'Starfish']},
    {'level': 2, 'name': 'Rat', 'options': ['Zebra', 'Cat', 'Koala', 'Donkey', 'Chimpanzee', 'Snail']},
    {'level': 2, 'name': 'Snake', 'options': ['Monkey', 'Cow', 'Spider', 'Goat', 'Polar Bear', 'Ape']},
    {'level': 2, 'name': 'Squirrel', 'options': ['Frog', 'Horse', 'Crab', 'Rat', 'Jaguar', 'Cockroach']},
    {'level': 3, 'name': 'Leopard', 'options': ['Goat', 'Fox', 'Chimpanzee', 'Jellyfish', 'Walrus', 'Turtle']},
    {'level': 3, 'name': 'Panda', 'options': ['Goat', 'Rhinocerous', 'Bobcat', 'Bobcat', 'Komodo Dragon', 'Armadillo']},
    {'level': 3, 'name': 'Ant', 'options': ['Rabbit', 'Pig', 'Chimpanzee', 'Jellyfish', 'Baboon', 'Hamster']},
    {'level': 3, 'name': 'Polar Bear', 'options': ['Donkey', 'Goat', 'Ant', 'Gorilla', 'Komodo Dragon', 'Sloth']},
    {'level': 3, 'name': 'Cockroach', 'options': ['Spider', 'Deer', 'Leopard', 'Gorilla', 'Turtle', 'Cheetah']},
    {'level': 3, 'name': 'Snail', 'options': ['Pig', 'Bull', 'Bobcat', 'Starfish', 'Beaver', 'Cheetah']},
    {'level': 3, 'name': 'Hyena', 'options': ['Donkey', 'Koala', 'Chimpanzee', 'Puma', 'Baboon', 'Hamster']},
    {'level': 3, 'name': 'Starfish', 'options': ['Goat', 'Pig', 'Leopard', 'Hyena', 'Gazelle', 'Beaver']},
    {'level': 3, 'name': 'Jaguar', 'options': ['Crab', 'Kangaroo', 'Puma', 'Snail', 'Hamster', 'Turtle']},
    {'level': 3, 'name': 'Puma', 'options': ['Pig', 'Crab', 'Snail', 'Hyena', 'Baboon', 'Armadillo']},
    {'level': 3, 'name': 'Bobcat', 'options': ['Rat', 'Bull', 'Jaguar', 'Chimpanzee', 'Komodo Dragon', 'Gerbil']},
    {'level': 3, 'name': 'Octopus', 'options': ['Fox', 'Koala', 'Ape', 'Puma', 'Impala', 'Gazelle']},
    {'level': 3, 'name': 'Ape', 'options': ['Bull', 'Hippopotamus', 'Ant', 'Bobcat', 'Komodo Dragon', 'Hamster']},
    {'level': 3, 'name': 'Jellyfish', 'options': ['Fox', 'Pig', 'Octopus', 'Panda', 'Hamster', 'Beaver']},
    {'level': 3, 'name': 'Gorilla', 'options': ['Pig', 'Deer', 'Snail', 'Chimpanzee', 'Impala', 'Baboon']},
    {'level': 3, 'name': 'Chimpanzee', 'options': ['Squirrel', 'Crab', 'Cockroach', 'Panda', 'Armadillo', 'Baboon']},
    {'level': 4, 'name': 'Impala', 'options': ['Starfish', 'Starfish', 'Beaver', 'Komodo Dragon', 'Wildebeest', 'Ferret']},
    {'level': 4, 'name': 'Walrus', 'options': ['Puma', 'Cockroach', 'Impala', 'Beaver', 'Lemur', 'Stingray']},
    {'level': 4, 'name': 'Komodo Dragon', 'options': ['Starfish', 'Jaguar', 'Gazelle', 'Cheetah', 'Eel', 'Ferret']},
    {'level': 4, 'name': 'Gerbil', 'options': ['Leopard', 'Ant', 'Impala', 'Beaver', 'Porcupine', 'Eel']},
    {'level': 4, 'name': 'Hamster', 'options': ['Jaguar', 'Gorilla', 'Gerbil', 'Baboon', 'Porcupine', 'Ferret']},
    {'level': 4, 'name': 'Cheetah', 'options': ['Bobcat', 'Puma', 'Hamster', 'Gerbil', 'Porcupine', 'Porcupine']},
    {'level': 4, 'name': 'Gazelle', 'options': ['Ant', 'Ape', 'Turtle', 'Komodo Dragon', 'Tapir', 'Stingray']},
    {'level': 4, 'name': 'Turtle', 'options': ['Jellyfish', 'Starfish', 'Hamster', 'Gazelle', 'Tapir', 'Eel']},
    {'level': 4, 'name': 'Baboon', 'options': ['Gorilla', 'Octopus', 'Armadillo', 'Turtle', 'Stingray', 'Alligator']},
    {'level': 4, 'name': 'Beaver', 'options': ['Octopus', 'Cockroach', 'Sloth', 'Armadillo', 'Stingray', 'Shark']},
    {'level': 4, 'name': 'Armadillo', 'options': ['Cockroach', 'Ape', 'Beaver', 'Beaver', 'Alligator', 'Porcupine']},
    {'level': 4, 'name': 'Sloth', 'options': ['Chimpanzee', 'Bobcat', 'Baboon', 'Beaver', 'Shark', 'Porcupine']},
    {'level': 5, 'name': 'Wildebeest', 'options': ['Sloth', 'Walrus', 'Alligator', 'Stingray', 'Sea Lion', 'Alpaca']},
    {'level': 5, 'name': 'Lemur', 'options': ['Gazelle', 'Gerbil', 'Porcupine', 'Alligator', 'Nilgai', 'Yak']},
    {'level': 5, 'name': 'Eel', 'options': ['Impala', 'Gerbil', 'Wildebeest', 'Seal', 'Wolverine', 'Sea Lion']},
    {'level': 5, 'name': 'Shark', 'options': ['Walrus', 'Komodo Dragon', 'Wildebeest', 'Alligator', 'Ibex', 'Nilgai']},
    {'level': 5, 'name': 'Raccoon', 'options': ['Walrus', 'Gazelle', 'Whale', 'Shark', 'Wolverine', 'Alpaca']},
    {'level': 5, 'name': 'Alligator', 'options': ['Gazelle', 'Gerbil', 'Lemur', 'Stingray', 'Wolverine', 'Alpaca']},
    {'level': 5, 'name': 'Seal', 'options': ['Hamster', 'Hamster', 'Wildebeest', 'Wildebeest', 'Alpaca', 'Sea Lion']},
    {'level': 5, 'name': 'Porcupine', 'options': ['Beaver', 'Gerbil', 'Lemur', 'Seal', 'Nilgai', 'Ibex']},
    {'level': 5, 'name': 'Ferret', 'options': ['Gerbil', 'Beaver', 'Lemur', 'Tapir', 'Wolverine', 'Seahorse']},
    {'level': 5, 'name': 'Whale', 'options': ['Gazelle', 'Impala', 'Stingray', 'Eel', 'Elk', 'Ibex']},
    {'level': 5, 'name': 'Tapir', 'options': ['Impala', 'Gerbil', 'Eel', 'Shark', 'Weasel', 'Seahorse']},
    {'level': 5, 'name': 'Stingray', 'options': ['Cheetah', 'Komodo Dragon', 'Porcupine', 'Shark', 'Yak', 'Wolverine']},
    {'level': 6, 'name': 'Alpaca', 'options': ['Ferret', 'Lemur', 'Weasel', 'Wolverine', 'Capybara', 'Coati']},
    {'level': 6, 'name': 'Yak', 'options': ['Lemur', 'Lemur', 'Weasel', 'Alpaca', 'Sea Otter', 'Snow Leopard']},
    {'level': 6, 'name': 'Sea Lion', 'options': ['Lemur', 'Tapir', 'Elk', 'Nilgai', 'Sea Cucumber', 'Capybara']},
    {'level': 6, 'name': 'Nilgai', 'options': ['Porcupine', 'Ferret', 'Ibex', 'Seahorse', 'Llama', 'Gharial']},
    {'level': 6, 'name': 'Seahorse', 'options': ['Shark', 'Shark', 'Alpaca', 'Elk', 'Squid', 'Gharial']},
    {'level': 6, 'name': 'Wolverine', 'options': ['Porcupine', 'Stingray', 'Seahorse', 'Seahorse', 'Capybara', 'Sea Otter']},
    {'level': 6, 'name': 'Wallaby', 'options': ['Wildebeest', 'Wildebeest', 'Sea Lion', 'Manatee', 'Orangutan', 'Capybara']},
    {'level': 6, 'name': 'Manatee', 'options': ['Alligator', 'Raccoon', 'Wolverine', 'Seahorse', 'Sea Otter', 'Gharial']},
    {'level': 6, 'name': 'Elk', 'options': ['Alligator', 'Alligator', 'Weasel', 'Sea Lion', 'Sea Cucumber', 'Capybara']},
    {'level': 6, 'name': 'Weasel', 'options': ['Stingray', 'Tapir', 'Wolverine', 'Yak', 'Guinea Pig', 'Sea Otter']},
    {'level': 6, 'name': 'Ibex', 'options': ['Eel', 'Tapir', 'Yak', 'Wallaby', 'Orangutan', 'Sea Cucumber']},
    {'level': 7, 'name': 'Capybara', 'options': ['Alpaca', 'Seahorse', 'Gharial', 'Orangutan', 'Iguana', 'Iguana']},
    {'level': 7, 'name': 'Coati', 'options': ['Weasel', 'Weasel', 'Llama', 'Llama', 'Sea Urchin', 'Saiga antelope']},
    {'level': 7, 'name': 'Snow Leopard', 'options': ['Sea Lion', 'Weasel', 'Gharial', 'Capybara', 'Saiga antelope', 'Hedgehog']},
    {'level': 7, 'name': 'Orangutan', 'options': ['Wolverine', 'Ibex', 'Snow Leopard', 'Snow Leopard', 'Saiga antelope', 'Saiga antelope']},
    {'level': 7, 'name': 'Bison', 'options': ['Yak', 'Ibex', 'Llama', 'Capybara', 'Pangolin', 'Lobster']},
    {'level': 7, 'name': 'Squid', 'options': ['Manatee', 'Wolverine', 'Llama', 'Bison', 'Barracuda', 'Badger']},
    {'level': 7, 'name': 'Sea Otter', 'options': ['Wolverine', 'Seahorse', 'Squid', 'Squid', 'Iguana', 'Lobster']},
    {'level': 7, 'name': 'Sea Cucumber', 'options': ['Wolverine', 'Elk', 'Orangutan', 'Snow Leopard', 'Wombat', 'Beetle']},
    {'level': 7, 'name': 'Gharial', 'options': ['Seahorse', 'Yak', 'Llama', 'Capybara', 'Iguana', 'Lobster']},
    {'level': 7, 'name': 'Llama', 'options': ['Elk', 'Seahorse', 'Bison', 'Capybara', 'Pangolin', 'Anteater']},
    {'level': 7, 'name': 'Guinea Pig', 'options': ['Seahorse', 'Manatee', 'Capybara', 'Bison', 'Wombat', 'Iguana']},
    {'level': 8, 'name': 'Saiga antelope', 'options': ['Coati', 'Guinea Pig', 'Beetle', 'Anteater', 'Okapi', 'Prairie Dog']},
    {'level': 8, 'name': 'Pangolin', 'options': ['Gharial', 'Llama', 'Saiga antelope', 'Iguana', 'Opossum', 'Prairie Dog']},
    {'level': 8, 'name': 'Sea Urchin', 'options': ['Guinea Pig', 'Coati', 'Barracuda', 'Iguana', 'Vaquita', 'Dugong']},
    {'level': 8, 'name': 'Anteater', 'options': ['Sea Otter', 'Gharial', 'Iguana', 'Badger', 'Mandrill', 'Okapi']},
    {'level': 8, 'name': 'Badger', 'options': ['Llama', 'Orangutan', 'Sea Urchin', 'Pangolin', 'Dugong', 'Prairie Dog']},
    {'level': 8, 'name': 'Wombat', 'options': ['Sea Otter', 'Coati', 'Beetle', 'Sea Urchin', 'Mandrill', 'Dugong']},
    {'level': 8, 'name': 'Beetle', 'options': ['Snow Leopard', 'Bison', 'Wombat', 'Saiga antelope', 'Dugong', 'Mandrill']},
    {'level': 8, 'name': 'Hedgehog', 'options': ['Sea Otter', 'Bison', 'Pangolin', 'Sea Urchin', 'Meerkat', 'Dugong']},
    {'level': 8, 'name': 'Barracuda', 'options': ['Llama', 'Guinea Pig', 'Iguana', 'Pangolin', 'Opossum', 'Meerkat']},
    {'level': 8, 'name': 'Lobster', 'options': ['Orangutan', 'Bison', 'Badger', 'Wombat', 'Prairie Dog', 'Dugong']},
    {'level': 8, 'name': 'Iguana', 'options': ['Coati', 'Squid', 'Sea Urchin', 'Beetle', 'Saola', 'Saola']},
    {'level': 9, 'name': 'Dugong', 'options': ['Badger', 'Lobster', 'Okapi', 'Mandrill', 'Binturong', 'Chinchilla']},
    {'level': 9, 'name': 'Saola', 'options': ['Anteater', 'Wombat', 'Opossum', 'Okapi', 'Sand Dollar', 'Addax']},
    {'level': 9, 'name': 'Guanaco', 'options': ['Hedgehog', 'Wombat', 'Meerkat', 'Otter', 'Chamois', 'Tarsier']},
    {'level': 9, 'name': 'Vaquita', 'options': ['Wombat', 'Hedgehog', 'Otter', 'Prairie Dog', 'Chinchilla', 'Chamois']},
    {'level': 9, 'name': 'Mandrill', 'options': ['Anteater', 'Barracuda', 'Saola', 'Dugong', 'Shrew', 'Kinkajou']},
    {'level': 9, 'name': 'Meerkat', 'options': ['Beetle', 'Beetle', 'Opossum', 'Dugong', 'Binturong', 'Addax']},
    {'level': 9, 'name': 'Okapi', 'options': ['Barracuda', 'Saiga antelope', 'Opossum', 'Opossum', 'Tarsier', 'Wombat']},
    {'level': 9, 'name': 'Opossum', 'options': ['Hedgehog', 'Lobster', 'Vaquita', 'Vaquita', 'Kinkajou', 'Sand Dollar']},
    {'level': 9, 'name': 'Otter', 'options': ['Barracuda', 'Beetle', 'Saola', 'Saola', 'Echidna', 'Chamois']},
    {'level': 9, 'name': 'Prairie Dog', 'options': ['Hedgehog', 'Lobster', 'Guanaco', 'Saola', 'Wombat', 'Sand Dollar']},
    {'level': 10, 'name': 'Wombat', 'options': ['Iguana', 'Saiga antelope', 'Vaquita', 'Guanaco', 'Chinchilla', 'Chinchilla']},
    {'level': 10, 'name': 'Shrew', 'options': ['Sea Urchin', 'Anteater', 'Okapi', 'Saola', 'Echidna', 'Binturong']},
    {'level': 10, 'name': 'Sand Dollar', 'options': ['Badger', 'Lobster', 'Saola', 'Opossum', 'Tarsier', 'Binturong']},
    {'level': 10, 'name': 'Echidna', 'options': ['Anteater', 'Iguana', 'Saola', 'Okapi', 'Sand Dollar', 'Chinchilla']},
    {'level': 10, 'name': 'Chamois', 'options': ['Badger', 'Lobster', 'Guanaco', 'Dugong', 'Wombat', 'Binturong']},
    {'level': 10, 'name': 'Binturong', 'options': ['Hedgehog', 'Hedgehog', 'Opossum', 'Otter', 'Echidna', 'Chinchilla']},
    {'level': 10, 'name': 'Chinchilla', 'options': ['Sea Urchin', 'Barracuda', 'Dugong', 'Okapi', 'Shrew', 'Binturong']},
    {'level': 10, 'name': 'Kinkajou', 'options': ['Anteater', 'Hedgehog', 'Mandrill', 'Mandrill', 'Binturong', 'Tarsier']},
    {'level': 10, 'name': 'Tarsier', 'options': ['Barracuda', 'Barracuda', 'Guanaco', 'Guanaco', 'Wombat', 'Sand Dollar']},
    {'level': 10, 'name': 'Addax', 'options': ['Pangolin', 'Pangolin', 'Prairie Dog', 'Vaquita', 'Chinchilla', 'Chinchilla']}
]

quiz = []

for animal in animals:
  curr = {}
  curr['options'] =  fetcher.fetch('animal', animal)
