import fetcher
import json


animals = [
    {'level': 1, 'name': 'Monkey', 'options': ['Donkey', 'Koala', 'Pig', 'Gorilla', 'Hamster', 'Porcupine', 'Bear']},
    {'level': 1, 'name': 'Buffalo', 'options': ['Elephant', 'Camel', 'Goat', 'Zebra', 'Cow', 'Donkey', 'Horse']},
    {'level': 1, 'name': 'Camel', 'options': ['Elephant', 'Dog', 'Giraffe', 'Pig', 'Baboon', 'Monkey']},
    {'level': 1, 'name': 'Cat', 'options': ['Goat', 'Panther', 'Lion', 'Tiger', 'Cheetah', 'Dog']},
    {'level': 1, 'name': 'Dog', 'options': ['Rat', 'Bear', 'Impala', 'Goat', 'Walrus', 'Fox']},
    {'level': 1, 'name': 'Tiger', 'options': ['Lion', 'Fox', 'Puma', 'Jaguar', 'Leopard', 'Deer']},
    {'level': 1, 'name': 'Lion', 'options': ['Tiger', 'Cow', 'Bear', 'Crocodile', 'Cockroach', 'Snail']},
    {'level': 1, 'name': 'Elephant', 'options': ['Tiger', 'Giraffe', 'Goat', 'Pig', 'Ant', 'Chimpanzee']},
    {'level': 1, 'name': 'Giraffe', 'options': ['Camel', 'Dog', 'Bear', 'Kangaroo', 'Hyena', 'Jaguar']},
    {'level': 1, 'name': 'Zebra', 'options': ['Camel', 'Lion', 'Cow', 'Squirrel', 'Snail', 'Panda']},
    {'level': 1, 'name': 'Sheep', 'options': ['Frog', 'Camel', 'Hippopotamus', 'Rhinocerous', 'Gorilla', 'Snail']},
    {'level': 1, 'name': 'Dolphin', 'options': ['Buffalo', 'Camel', 'Squirrel', 'Rabbit', 'Puma', 'Jaguar']},
    {'level': 1, 'name': 'Cow', 'options': ['Elephant', 'Frog', 'Donkey', 'Goat', 'Polar Bear', 'Hyena']},
    {'level': 1, 'name': 'Horse', 'options': ['Zebra', 'Tiger', 'Koala', 'Rabbit', 'Buffalo', 'Bobcat']},
    {'level': 1, 'name': 'Frog', 'options': ['Cat', 'Cow', 'Crocodile', 'Rabbit', 'Hyena', 'Cockroach']},
    {'level': 2, 'name': 'Donkey', 'options': ['Lion', 'Monkey', 'Cow', 'Crocodile', 'Jellyfish', 'Dog']},
    {'level': 2, 'name': 'Crab', 'options': ['Buffalo', 'Monkey', 'Squirrel', 'Deer', 'Leopard', 'Snail']},
    {'level': 2, 'name': 'Bear', 'options': ['Lion', 'Monkey', 'Crocodile', 'Rabbit', 'Bobcat', 'Gorilla']},
    {'level': 2, 'name': 'Hippopotamus', 'options': ['Giraffe', 'Buffalo', 'Goat', 'Crab', 'Bobcat', 'Polar Bear']},
    {'level': 2, 'name': 'Rhinocerous', 'options': ['Sheep', 'Dolphin', 'Cow', 'Goat', 'Ant', 'Polar Bear']},
    {'level': 2, 'name': 'Koala', 'options': ['Zebra', 'Camel', 'Deer', 'Crocodile', 'Bobcat', 'Starfish']},
    {'level': 2, 'name': 'Kangaroo', 'options': ['Dolphin', 'Camel', 'Rabbit', 'Goat', 'Bobcat', 'Jellyfish']},
    {'level': 2, 'name': 'Spider', 'options': ['Monkey', 'Zebra', 'Pig', 'Rabbit', 'Jellyfish', 'Gorilla']},
    {'level': 2, 'name': 'Pig', 'options': ['Camel', 'Frog', 'Bear', 'Kangaroo', 'Octopus', 'Leopard']},
    {'level': 2, 'name': 'Crocodile', 'options': ['Tiger', 'Dog', 'Pig', 'Rabbit', 'Ant', 'Cockroach']},
    {'level': 2, 'name': 'Goat', 'options': ['Dolphin', 'Cat', 'Kangaroo', 'Hippopotamus', 'Hyena', 'Cockroach']},
    {'level': 2, 'name': 'Rabbit', 'options': ['Frog', 'Cow', 'Fox', 'Crocodile', 'Chimpanzee', 'Snail']},
    {'level': 2, 'name': 'Fox', 'options': ['Camel', 'Tiger', 'Kangaroo', 'Rabbit', 'Chimpanzee', 'Panda']},
    {'level': 2, 'name': 'Deer', 'options': ['Camel', 'Cat', 'Fox', 'Rat', 'Cockroach', 'Snail']},
    {'level': 2, 'name': 'Rat', 'options': ['Camel', 'Giraffe', 'Fox', 'Hippopotamus', 'Puma', 'Dog']},
    {'level': 2, 'name': 'Snake', 'options': ['Tiger', 'Zebra', 'Fox', 'Rat', 'Ant', 'Puma']},
    {'level': 2, 'name': 'Squirrel', 'options': ['Camel', 'Cow', 'Goat', 'Rhinocerous', 'Hyena', 'Panda']},
    {'level': 3, 'name': 'Leopard', 'options': ['Hippopotamus', 'Snake', 'Chimpanzee', 'Bobcat', 'Gazelle', 'Sloth']},
    {'level': 3, 'name': 'Panda', 'options': ['Rhinocerous', 'Hippopotamus', 'Octopus', 'Chimpanzee', 'Cheetah', 'Sloth']},
    {'level': 3, 'name': 'Ant', 'options': ['Deer', 'Fox', 'Hyena', 'Puma', 'Turtle', 'Walrus']},
    {'level': 3, 'name': 'Polar Bear', 'options': ['Spider', 'Donkey', 'Panda', 'Ant', 'Sloth', 'Komodo Dragon']},
    {'level': 3, 'name': 'Cockroach', 'options': ['Rhinocerous', 'Pig', 'Puma', 'Hyena', 'Gazelle', 'Cheetah']},
    {'level': 3, 'name': 'Snail', 'options': ['Koala', 'Crocodile', 'Chimpanzee', 'Jellyfish', 'Komodo Dragon', 'Gazelle']},
    {'level': 3, 'name': 'Hyena', 'options': ['Cow', 'Hippopotamus', 'Snail', 'Bobcat', 'Walrus', 'Hamster']},
    {'level': 3, 'name': 'Starfish', 'options': ['Pig', 'Squirrel', 'Ant', 'Puma', 'Baboon', 'Hamster']},
    {'level': 3, 'name': 'Jaguar', 'options': ['Hippopotamus', 'Crab', 'Polar Bear', 'Chimpanzee', 'Walrus', 'Impala']},
    {'level': 3, 'name': 'Puma', 'options': ['Kangaroo', 'Goat', 'Panda', 'Bobcat', 'Hamster', 'Gazelle']},
    {'level': 3, 'name': 'Bobcat', 'options': ['Goat', 'Snake', 'Jellyfish', 'Gorilla', 'Impala', 'Turtle']},
    {'level': 3, 'name': 'Octopus', 'options': ['Crab', 'Pig', 'Cockroach', 'Bobcat', 'Gerbil', 'Beaver']},
    {'level': 3, 'name': 'Jellyfish', 'options': ['Koala', 'Bear', 'Ant', 'Crab', 'Baboon', 'Gazelle']},
    {'level': 3, 'name': 'Gorilla', 'options': ['Rhinocerous', 'Crab', 'Hyena', 'Octopus', 'Cheetah', 'Armadillo']},
    {'level': 3, 'name': 'Chimpanzee', 'options': ['Squirrel', 'Donkey', 'Bobcat', 'Puma', 'Turtle', 'Hamster']},
    {'level': 4, 'name': 'Impala', 'options': ['Puma', 'Snail', 'Armadillo', 'Cheetah', 'Ferret', 'Shark']},
    {'level': 4, 'name': 'Walrus', 'options': ['Chimpanzee', 'Gorilla', 'Hamster', 'Cheetah', 'Porcupine', 'Stingray']},
    {'level': 4, 'name': 'Komodo Dragon', 'options': ['Panda', 'Jellyfish', 'Armadillo', 'Hamster', 'Wildebeest', 'Eel']},
    {'level': 4, 'name': 'Gerbil', 'options': ['Starfish', 'Bobcat', 'Hamster', 'Baboon', 'Raccoon', 'Shark']},
    {'level': 4, 'name': 'Cheetah', 'options': ['Starfish', 'Jellyfish', 'Gazelle', 'Hamster', 'Lemur', 'Seal']},
    {'level': 4, 'name': 'Gazelle', 'options': ['Chimpanzee', 'Octopus', 'Impala', 'Baboon', 'Raccoon', 'Eel']},
    {'level': 4, 'name': 'Turtle', 'options': ['Leopard', 'Snail', 'Walrus', 'Gerbil', 'Ferret', 'Seal']},
    {'level': 4, 'name': 'Baboon', 'options': ['Jellyfish', 'Panda', 'Cheetah', 'Walrus', 'Wildebeest', 'Raccoon']},
    {'level': 4, 'name': 'Beaver', 'options': ['Puma', 'Chimpanzee', 'Gazelle', 'Walrus', 'Lemur', 'Ferret']},
    {'level': 4, 'name': 'Armadillo', 'options': ['Puma', 'Chimpanzee', 'Gerbil', 'Komodo Dragon', 'Tapir', 'Seal']},
    {'level': 4, 'name': 'Sloth', 'options': ['Puma', 'Polar Bear', 'Turtle', 'Beaver', 'Seal', 'Stingray']},
    {'level': 4, 'name': 'Hamster', 'options': ['Bobcat', 'Octopus', 'Komodo Dragon', 'Baboon', 'Whale', 'Raccoon']},
    {'level': 5, 'name': 'Wildebeest', 'options': ['Impala', 'Cheetah', 'Tapir', 'Porcupine', 'Wallaby', 'Ibex']},
    {'level': 5, 'name': 'Lemur', 'options': ['Beaver', 'Hamster', 'Ferret', 'Porcupine', 'Ibex', 'Weasel']},
    {'level': 5, 'name': 'Eel', 'options': ['Gerbil', 'Komodo Dragon', 'Whale', 'Wildebeest', 'Sea Lion', 'Elk']},
    {'level': 5, 'name': 'Shark', 'options': ['Armadillo', 'Gerbil', 'Seal', 'Lemur', 'Weasel', 'Alpaca']},
    {'level': 5, 'name': 'Raccoon', 'options': ['Gazelle', 'Armadillo', 'Eel', 'Whale', 'Alpaca', 'Yak']},
    {'level': 5, 'name': 'Alligator', 'options': ['Gazelle', 'Sloth', 'Porcupine', 'Lemur', 'Ibex', 'Yak']},
    {'level': 5, 'name': 'Seal', 'options': ['Turtle', 'Sloth', 'Ferret', 'Wildebeest', 'Wallaby', 'Ibex']},
    {'level': 5, 'name': 'Porcupine', 'options': ['Impala', 'Baboon', 'Tapir', 'Shark', 'Wallaby', 'Manatee']},
    {'level': 5, 'name': 'Ferret', 'options': ['Komodo Dragon', 'Gerbil', 'Alligator', 'Whale', 'Elk', 'Wallaby']},
    {'level': 5, 'name': 'Whale', 'options': ['Beaver', 'Impala', 'Lemur', 'Stingray', 'Manatee', 'Wolverine']},
    {'level': 5, 'name': 'Tapir', 'options': ['Cheetah', 'Sloth', 'Eel', 'Wildebeest', 'Weasel', 'Wallaby']},
    {'level': 5, 'name': 'Stingray', 'options': ['Hamster', 'Gazelle', 'Seal', 'Ferret', 'Wallaby', 'Manatee']},
    {'level': 6, 'name': 'Alpaca', 'options': ['Eel', 'Raccoon', 'Nilgai', 'Elk', 'Sea Otter', 'Llama']},
    {'level': 6, 'name': 'Yak', 'options': ['Shark', 'Eel', 'Weasel', 'Wolverine', 'Gharial', 'Orangutan']},
    {'level': 6, 'name': 'Sea Lion', 'options': ['Ferret', 'Whale', 'Yak', 'Wolverine', 'Guinea Pig', 'Sea Otter']},
    {'level': 6, 'name': 'Nilgai', 'options': ['Alligator', 'Raccoon', 'Ibex', 'Elk', 'Snow Leopard', 'Sea Cucumber']},
    {'level': 6, 'name': 'Seahorse', 'options': ['Lemur', 'Shark', 'Manatee', 'Yak', 'Snow Leopard', 'Squid']},
    {'level': 6, 'name': 'Wolverine', 'options': ['Whale', 'Porcupine', 'Weasel', 'Wallaby', 'Bison', 'Orangutan']},
    {'level': 6, 'name': 'Wallaby', 'options': ['Eel', 'Alligator', 'Ibex', 'Yak', 'Squid', 'Snow Leopard']},
    {'level': 6, 'name': 'Manatee', 'options': ['Lemur', 'Wildebeest', 'Wallaby', 'Wolverine', 'Sea Otter', 'Orangutan']},
    {'level': 6, 'name': 'Elk', 'options': ['Eel', 'Lemur', 'Ibex', 'Manatee', 'Sea Otter', 'Sea Cucumber']},
    {'level': 6, 'name': 'Weasel', 'options': ['Stingray', 'Wildebeest', 'Seahorse', 'Alpaca', 'Sea Otter', 'Sea Cucumber']},
    {'level': 6, 'name': 'Ibex', 'options': ['Alligator', 'Tapir', 'Wallaby', 'Elk', 'Orangutan', 'Snow Leopard']},
    {'level': 7, 'name': 'Capybara', 'options': ['Manatee', 'Weasel', 'Llama', 'Snow Leopard', 'Barracuda', 'Lobster']},
    {'level': 7, 'name': 'Coati', 'options': ['Manatee', 'Wolverine', 'Gharial', 'Capybara', 'Lobster', 'Wombat']},
    {'level': 7, 'name': 'Snow Leopard', 'options': ['Wolverine', 'Wallaby', 'Capybara', 'Sea Cucumber', 'Anteater', 'Lobster']},
    {'level': 7, 'name': 'Orangutan', 'options': ['Alpaca', 'Ibex', 'Llama', 'Sea Cucumber', 'Iguana', 'Badger']},
    {'level': 7, 'name': 'Bison', 'options': ['Elk', 'Yak', 'Snow Leopard', 'Capybara', 'Wombat', 'Beetle']},
    {'level': 7, 'name': 'Squid', 'options': ['Wolverine', 'Elk', 'Coati', 'Gharial', 'Saiga antelope', 'Sea Urchin']},
    {'level': 7, 'name': 'Sea Otter', 'options': ['Ibex', 'Elk', 'Squid', 'Coati', 'Pangolin', 'Sea Urchin']},
    {'level': 7, 'name': 'Sea Cucumber', 'options': ['Alpaca', 'Elk', 'Bison', 'Sea Otter', 'Anteater', 'Pangolin']},
    {'level': 7, 'name': 'Gharial', 'options': ['Ibex', 'Yak', 'Squid', 'Coati', 'Sea Urchin', 'Saiga antelope']},
    {'level': 7, 'name': 'Llama', 'options': ['Alpaca', 'Weasel', 'Orangutan', 'Snow Leopard', 'Saiga antelope', 'Wombat']},
    {'level': 7, 'name': 'Guinea Pig', 'options': ['Yak', 'Seahorse', 'Gharial', 'Sea Cucumber', 'Iguana', 'Badger']},
    {'level': 8, 'name': 'Saiga antelope', 'options': ['Bison', 'Gharial', 'Barracuda', 'Pangolin', 'Dugong', 'Prairie Dog']},
    {'level': 8, 'name': 'Pangolin', 'options': ['Snow Leopard', 'Llama', 'Lobster', 'Iguana', 'Saola', 'Otter']},
    {'level': 8, 'name': 'Sea Urchin', 'options': ['Squid', 'Guinea Pig', 'Beetle', 'Hedgehog', 'Otter', 'Guanaco']},
    {'level': 8, 'name': 'Anteater', 'options': ['Coati', 'Gharial', 'Beetle', 'Wombat', 'Dugong', 'Otter']},
    {'level': 8, 'name': 'Badger', 'options': ['Snow Leopard', 'Guinea Pig', 'Beetle', 'Barracuda', 'Vaquita', 'Prairie Dog']},
    {'level': 8, 'name': 'Beetle', 'options': ['Bison', 'Sea Cucumber', 'Saiga antelope', 'Pangolin', 'Mandrill', 'Prairie Dog']},
    {'level': 8, 'name': 'Hedgehog', 'options': ['Sea Cucumber', 'Gharial', 'Sea Urchin', 'Anteater', 'Okapi', 'Otter']},
    {'level': 8, 'name': 'Barracuda', 'options': ['Snow Leopard', 'Bison', 'Pangolin', 'Lobster', 'Meerkat', 'Mandrill']},
    {'level': 8, 'name': 'Lobster', 'options': ['Bison', 'Sea Otter', 'Saiga antelope', 'Hedgehog', 'Saola', 'Dugong']},
    {'level': 8, 'name': 'Iguana', 'options': ['Capybara', 'Bison', 'Anteater', 'Lobster', 'Otter', 'Prairie Dog']},
    {'level': 9, 'name': 'Dugong', 'options': ['Hedgehog', 'Wombat', 'Guanaco', 'Opossum', 'Addax', 'Shrew']},
    {'level': 9, 'name': 'Saola', 'options': ['Wombat', 'Badger', 'Prairie Dog', 'Meerkat', 'Addax', 'Echidna']},
    {'level': 9, 'name': 'Guanaco', 'options': ['Anteater', 'Sea Urchin', 'Okapi', 'Vaquita', 'Tarsier', 'Binturong']},
    {'level': 9, 'name': 'Vaquita', 'options': ['Anteater', 'Iguana', 'Mandrill', 'Dugong', 'Echidna', 'Kinkajou']},
    {'level': 9, 'name': 'Mandrill', 'options': ['Anteater', 'Barracuda', 'Vaquita', 'Dugong', 'Wombat', 'Chamois']},
    {'level': 9, 'name': 'Meerkat', 'options': ['Anteater', 'Pangolin', 'Opossum', 'Prairie Dog', 'Shrew', 'Chinchilla']},
    {'level': 9, 'name': 'Okapi', 'options': ['Saiga antelope', 'Barracuda', 'Guanaco', 'Meerkat', 'Sand Dollar', 'Chamois']},
    {'level': 9, 'name': 'Opossum', 'options': ['Wombat', 'Barracuda', 'Vaquita', 'Saola', 'Sand Dollar', 'Wombat']},
    {'level': 9, 'name': 'Otter', 'options': ['Pangolin', 'Anteater', 'Guanaco', 'Vaquita', 'Addax', 'Echidna']},
    {'level': 9, 'name': 'Prairie Dog', 'options': ['Barracuda', 'Hedgehog', 'Otter', 'Saola', 'Chinchilla', 'Addax']},
    {'level': 10, 'name': 'Wombat', 'options': ['Saiga antelope', 'Iguana', 'Saola', 'Meerkat', 'Shrew', 'Chamois']},
    {'level': 10, 'name': 'Shrew', 'options': ['Hedgehog', 'Saiga antelope', 'Vaquita', 'Okapi', 'Tarsier', 'Chinchilla']},
    {'level': 10, 'name': 'Sand Dollar', 'options': ['Pangolin', 'Barracuda', 'Vaquita', 'Otter', 'Echidna', 'Chamois']},
    {'level': 10, 'name': 'Echidna', 'options': ['Badger', 'Beetle', 'Guanaco', 'Okapi', 'Kinkajou', 'Chinchilla']},
    {'level': 10, 'name': 'Chamois', 'options': ['Hedgehog', 'Pangolin', 'Opossum', 'Okapi', 'Tarsier', 'Wombat']},
    {'level': 10, 'name': 'Binturong', 'options': ['Wombat', 'Lobster', 'Opossum', 'Dugong', 'Chamois', 'Kinkajou']},
    {'level': 10, 'name': 'Chinchilla', 'options': ['Sea Urchin', 'Barracuda', 'Vaquita', 'Dugong', 'Tarsier', 'Kinkajou']},
    {'level': 10, 'name': 'Kinkajou', 'options': ['Barracuda', 'Badger', 'Opossum', 'Vaquita', 'Shrew', 'Chamois']},
    {'level': 10, 'name': 'Tarsier', 'options': ['Badger', 'Lobster', 'Prairie Dog', 'Vaquita', 'Echidna', 'Shrew']},
    {'level': 10, 'name': 'Addax', 'options': ['Anteater', 'Saiga antelope', 'Meerkat', 'Otter', 'Chinchilla', 'Kinkajou']}
]

quiz = []
for animal in animals:
    animal['urls'] = fetcher.fetch('animal', animal['name'])
    quiz.append(animal)

with open("animals3.json", "w") as f:
    f.write(json.dumps(quiz))
