import json

import fetcher


birds = [
    {'level': 1, 'name': 'Parrot', 'options': ['Pigeon', 'Owl', 'Woodpecker', 'Pelican', 'Raven', 'Goose']},
    {'level': 1, 'name': 'Pigeon', 'options': ['Owl', 'Peacock', 'African Spoonbill', 'Sparrow', 'Emu', 'Vulture']},
    {'level': 1, 'name': 'Duck', 'options': ['Peacock', 'Crow', 'Hummingbird', 'Blue Jay', 'Crane', 'Mallard']},
    {'level': 1, 'name': 'Chicken', 'options': ['Crow', 'Parrot', 'Wild Turkey', 'Grey-headed Dove', 'Flamingo', 'Seagull']},
    {'level': 1, 'name': 'Crow', 'options': ['Pigeon', 'Penguin', 'Blue Jay', 'Kingfisher', 'Flamingo', 'Seagull']},
    {'level': 1, 'name': 'Peacock', 'options': ['Parrot', 'Crow', 'Hummingbird', 'Woodpecker', 'Crane', 'Emu']},
    {'level': 1, 'name': 'Swan', 'options': ['Duck', 'Crow', 'Woodpecker', 'Wild Turkey', 'Crane', 'Raven']},
    {'level': 1, 'name': 'Owl', 'options': ['Swan', 'Peacock', 'Rainbow Lorikeet', 'Grey-headed Dove', 'Mallard', 'Emu']},
    {'level': 1, 'name': 'Penguin', 'options': ['Peacock', 'Pigeon', 'Kingfisher', 'Eagle', 'Mallard', 'Raven']},
    {'level': 1, 'name': 'Ostrich', 'options': ['Duck', 'Penguin', 'African Spoonbill', 'Rainbow Lorikeet', 'Mallard', 'Raven']},
    {'level': 2, 'name': 'Eagle', 'options': ['Pigeon', 'Chicken', 'Pelican', 'Rainbow Lorikeet', 'Goose', 'Emu']},
    {'level': 2, 'name': 'Hummingbird', 'options': ['Peacock', 'Crow', 'African Spoonbill', 'Woodpecker', 'Goldfinch', 'Seagull']},
    {'level': 2, 'name': 'Pelican', 'options': ['Owl', 'Crow', 'Kingfisher', 'Rainbow Lorikeet', 'Crane', 'Seagull']},
    {'level': 2, 'name': 'Sparrow', 'options': ['Chicken', 'Parrot', 'Blue Jay', 'Rainbow Lorikeet', 'Vulture', 'Goose']},
    {'level': 2, 'name': 'Wild Turkey', 'options': ['Owl', 'Parrot', 'Grey-headed Dove', 'Pelican', 'Crane', 'Goose']},
    {'level': 2, 'name': 'Grey-headed Dove', 'options': ['Parrot', 'Pigeon', 'African Spoonbill', 'Kingfisher', 'Goldfinch', 'Vulture']},
    {'level': 2, 'name': 'Kingfisher', 'options': ['Swan', 'Ostrich', 'Blue Jay', 'African Spoonbill', 'Emu', 'Crane']},
    {'level': 2, 'name': 'Woodpecker', 'options': ['Owl', 'Peacock', 'Rainbow Lorikeet', 'Pelican', 'Falcon', 'Emu']},
    {'level': 2, 'name': 'African Spoonbill', 'options': ['Peacock', 'Penguin', 'Blue Jay', 'Wild Turkey', 'Goldfinch', 'Seagull']},
    {'level': 2, 'name': 'Rainbow Lorikeet', 'options': ['Ostrich', 'Owl', 'Grey-headed Dove', 'Sparrow', 'Falcon', 'Emu']},
    {'level': 2, 'name': 'Blue Jay', 'options': ['Owl', 'Pigeon', 'African Spoonbill', 'Rainbow Lorikeet', 'Flamingo', 'Goose']},
    {'level': 3, 'name': 'Vulture', 'options': ['Rainbow Lorikeet', 'Grey-headed Dove', 'Raven', 'Goose', 'Common Starling', 'Cock-of-the-rock']},
    {'level': 3, 'name': 'Seagull', 'options': ['Woodpecker', 'Sparrow', 'Goldfinch', 'Flamingo', 'Dalmatian Pelican', 'Turkey vulture']},
    {'level': 3, 'name': 'Emu', 'options': ['Pelican', 'Blue Jay', 'Vulture', 'Flamingo', 'Goldcrest', 'Myna']},
    {'level': 3, 'name': 'Flamingo', 'options': ['African Spoonbill', 'Sparrow', 'Mallard', 'Falcon', 'Turkey vulture', 'Java Sparrow']},
    {'level': 3, 'name': 'Mallard', 'options': ['Grey-headed Dove', 'Woodpecker', 'Vulture', 'Raven', 'Hornbill', 'Golden Eagle']},
    {'level': 3, 'name': 'Goose', 'options': ['Pelican', 'Hummingbird', 'Goldfinch', 'Raven', 'Turkey vulture', 'Zebra Dove']},
    {'level': 3, 'name': 'Crane', 'options': ['Eagle', 'Sparrow', 'Vulture', 'Falcon', 'Zebra Dove', 'Hornbill']},
    {'level': 3, 'name': 'Raven', 'options': ['Sparrow', 'Hummingbird', 'Goose', 'Mallard', 'Golden Eagle', 'Cock-of-the-rock']},
    {'level': 3, 'name': 'Falcon', 'options': ['Pelican', 'Eagle', 'Vulture', 'Emu', 'Zebra Dove', 'Dalmatian Pelican']},
    {'level': 3, 'name': 'Goldfinch', 'options': ['Eagle', 'Blue Jay', 'Crane', 'Mallard', 'Turkey vulture', 'Hornbill']},
    {'level': 4, 'name': 'Myna', 'options': ['Seagull', 'Raven', 'Golden Eagle', 'Cock-of-the-rock', 'Shoebill', 'Indian Roller']},
    {'level': 4, 'name': 'Common Starling', 'options': ['Flamingo', 'Goose', 'Cock-of-the-rock', 'Java Sparrow', 'Cuckoo', 'Hyacinth Macaw']},
    {'level': 4, 'name': 'Golden Eagle', 'options': ['Crane', 'Emu', 'Hornbill', 'Zebra Dove', 'Coal Tit', 'Shoebill']},
    {'level': 4, 'name': 'Turkey vulture', 'options': ['Raven', 'Falcon', 'Common Tern', 'Myna', 'Eurasian Eagle-owl', 'Magpie']},
    {'level': 4, 'name': 'Zebra Dove', 'options': ['Mallard', 'Raven', 'Golden Eagle', 'Myna', 'Coal Tit', 'Ruby-throated Hummingbird']},
    {'level': 4, 'name': 'Hornbill', 'options': ['Goose', 'Falcon', 'Golden Eagle', 'Java Sparrow', 'Indian Roller', 'Magpie']},
    {'level': 4, 'name': 'Goldcrest', 'options': ['Crane', 'Falcon', 'Cock-of-the-rock', 'Java Sparrow', 'Eurasian Bullfinch', 'Shoebill']},
    {'level': 4, 'name': 'Dalmatian Pelican', 'options': ['Goose', 'Vulture', 'Java Sparrow', 'Common Starling', 'Hyacinth Macaw', 'Eurasian Bullfinch']},
    {'level': 4, 'name': 'Cock-of-the-rock', 'options': ['Flamingo', 'Emu', 'Golden Eagle', 'Dalmatian Pelican', 'Blue Whistling Thrush', 'Magpie']},
    {'level': 4, 'name': 'Common Tern', 'options': ['Raven', 'Seagull', 'Common Starling', 'Goldcrest', 'Shoebill', 'Laughing Kookaburra']},
    {'level': 4, 'name': 'Java Sparrow', 'options': ['Goldfinch', 'Seagull', 'Myna', 'Dalmatian Pelican', 'Ruby-throated Hummingbird', 'Blue Whistling Thrush']},
    {'level': 5, 'name': 'Cuckoo', 'options': ['Dalmatian Pelican', 'Myna', 'Eurasian Eagle-owl', 'Laughing Kookaburra', 'Honeyeater', 'Gyrfalcon']},
    {'level': 5, 'name': 'Indian Roller', 'options': ['Goldcrest', 'Myna', 'Magpie', 'Eurasian Eagle-owl', 'Mockingbird', 'Thornbill']},
    {'level': 5, 'name': 'Magpie', 'options': ['Cock-of-the-rock', 'Goldcrest', 'Blue Whistling Thrush', 'Eurasian Eagle-owl', 'Tit', 'Mockingbird']},
    {'level': 5, 'name': 'Ruby-throated Hummingbird', 'options': ['Common Starling', 'Goldcrest', 'Eurasian Bullfinch', 'Cuckoo', 'Mockingbird', 'Finch']},
    {'level': 5, 'name': 'Hyacinth Macaw', 'options': ['Myna', 'Common Tern', 'Indian Roller', 'Eurasian Eagle-owl', 'Toucan', 'Gyrfalcon']},
    {'level': 5, 'name': 'Eurasian Eagle-owl', 'options': ['Common Tern', 'Hornbill', 'Eurasian Bullfinch', 'Shoebill', 'Tit', 'Toucan']},
    {'level': 5, 'name': 'Coal Tit', 'options': ['Myna', 'Goldcrest', 'Laughing Kookaburra', 'Hyacinth Macaw', 'Honeyeater', 'Koel']},
    {'level': 5, 'name': 'Laughing Kookaburra', 'options': ['Java Sparrow', 'Golden Eagle', 'Cuckoo', 'Eurasian Eagle-owl', 'Bulbul', 'Koel']},
    {'level': 5, 'name': 'Eurasian Bullfinch', 'options': ['Hornbill', 'Myna', 'Indian Roller', 'Hyacinth Macaw', 'Toucan', 'Gyrfalcon']},
    {'level': 5, 'name': 'Shoebill', 'options': ['Dalmatian Pelican', 'Goldcrest', 'Laughing Kookaburra', 'Magpie', 'Tit', 'Honeyeater']},
    {'level': 5, 'name': 'Blue Whistling Thrush', 'options': ['Golden Eagle', 'Cock-of-the-rock', 'Eurasian Bullfinch', 'Cuckoo', 'Mockingbird', 'Gyrfalcon']},
    {'level': 6, 'name': 'Mockingbird', 'options': ['Coal Tit', 'Hyacinth Macaw', 'Gyrfalcon', 'Toucan', 'Pipit', 'Jungle Myna']},
    {'level': 6, 'name': 'Finch', 'options': ['Laughing Kookaburra', 'Coal Tit', 'Mockingbird', 'Honeyeater', 'Jungle Myna', 'Bustard']},
    {'level': 6, 'name': 'Bulbul', 'options': ['Indian Roller', 'Cuckoo', 'Toucan', 'Tit', 'Galah', 'Macaw']},
    {'level': 6, 'name': 'Thornbill', 'options': ['Eurasian Eagle-owl', 'Hyacinth Macaw', 'Tit', 'Toucan', 'Pipit', 'Galah']},
    {'level': 6, 'name': 'Honeyeater', 'options': ['Eurasian Bullfinch', 'Cuckoo', 'European Roller', 'Mockingbird', 'Bustard', 'Oriole']},
    {'level': 6, 'name': 'Tit', 'options': ['Shoebill', 'Ruby-throated Hummingbird', 'Mockingbird', 'Finch', 'Northern Shoveler', 'Pipit']},
    {'level': 6, 'name': 'European Roller', 'options': ['Shoebill', 'Cuckoo', 'Koel', 'Gyrfalcon', 'Oriole', 'Bustard']},
    {'level': 6, 'name': 'Toucan', 'options': ['Ruby-throated Hummingbird', 'Magpie', 'Honeyeater', 'Bulbul', 'Oriole', 'Macaw']},
    {'level': 6, 'name': 'Gyrfalcon', 'options': ['Shoebill', 'Ruby-throated Hummingbird', 'European Roller', 'Thornbill', 'Bustard', 'Northern Shoveler']},
    {'level': 6, 'name': 'Koel', 'options': ['Coal Tit', 'Eurasian Eagle-owl', 'Gyrfalcon', 'Honeyeater', 'Bustard', 'Galah']},
    {'level': 7, 'name': 'Oriole', 'options': ['Koel', 'Honeyeater', 'Albatross', 'Jungle Myna', 'Merlin', 'Rhea']},
    {'level': 7, 'name': 'Jungle Myna', 'options': ['Koel', 'Mockingbird', 'Pipit', 'Northern Shoveler', 'Merlin', 'Hawfinch']},
    {'level': 7, 'name': 'Pipit', 'options': ['Tit', 'Thornbill', 'Northern Shoveler', 'Galah', 'Gadwall', 'Brambling']},
    {'level': 7, 'name': 'Catbird', 'options': ['Gyrfalcon', 'Mockingbird', 'Jungle Myna', 'Bustard', 'Secretarybird', 'Rhea']},
    {'level': 7, 'name': 'Northern Shoveler', 'options': ['Mockingbird', 'Koel', 'Catbird', 'Jungle Myna', 'Rhea', 'Secretarybird']},
    {'level': 7, 'name': 'Macaw', 'options': ['Bulbul', 'Tit', 'Galah', 'Albatross', 'Rhea', 'Merlin']},
    {'level': 7, 'name': 'Robin', 'options': ['Gyrfalcon', 'Tit', 'Galah', 'Bustard', 'Teal', 'Rhea']},
    {'level': 7, 'name': 'Albatross', 'options': ['Gyrfalcon', 'European Roller', 'Bustard', 'Northern Shoveler', 'Brambling', 'Canary']},
    {'level': 7, 'name': 'Bustard', 'options': ['Finch', 'Honeyeater', 'Macaw', 'Galah', 'Merlin', 'Brambling']},
    {'level': 7, 'name': 'Galah', 'options': ['Thornbill', 'Mockingbird', 'Northern Shoveler', 'Jungle Myna', 'Canary', 'Secretarybird']},
    {'level': 8, 'name': 'Teal', 'options': ['Jungle Myna', 'Catbird', 'King Quail', 'Brambling', 'Kori Bustard', 'Palmchat']},
    {'level': 8, 'name': 'Rhea', 'options': ['Pipit', 'Albatross', 'Brambling', 'Secretarybird', 'Stork', 'Kori Bustard']},
    {'level': 8, 'name': 'Willow Tit', 'options': ['Jungle Myna', 'Albatross', 'Gadwall', 'Rhea', 'Smew', 'Palmchat']},
    {'level': 8, 'name': 'Merlin', 'options': ['Jungle Myna', 'Catbird', 'Canary', 'Secretarybird', 'Jabiru', 'Brolga']},
    {'level': 8, 'name': 'Secretarybird', 'options': ['Macaw', 'Catbird', 'Gadwall', 'Teal', 'Bunting', 'Jabiru']},
    {'level': 8, 'name': 'Gadwall', 'options': ['Galah', 'Northern Shoveler', 'Merlin', 'King Quail', 'Condor', 'Smew']},
    {'level': 8, 'name': 'Brambling', 'options': ['Bustard', 'Catbird', 'Hawfinch', 'Gadwall', 'Gannet', 'Jabiru']},
    {'level': 8, 'name': 'King Quail', 'options': ['Robin', 'Albatross', 'Rhea', 'Brambling', 'Stork', 'Jabiru']},
    {'level': 8, 'name': 'Hawfinch', 'options': ['Macaw', 'Bustard', 'Gadwall', 'King Quail', 'Palmchat', 'Brolga']},
    {'level': 8, 'name': 'Canary', 'options': ['Pipit', 'Northern Shoveler', 'Rhea', 'Secretarybird', 'Kori Bustard', 'Palmchat']},
    {'level': 9, 'name': 'Jay', 'options': ['Willow Tit', 'King Quail', 'Jabiru', 'Kea', 'Shama', 'Dunnock']},
    {'level': 9, 'name': 'Condor', 'options': ['King Quail', 'Secretarybird', 'Kori Bustard', 'Brolga', 'Cassowary', 'Saddle-billed Stork']},
    {'level': 9, 'name': 'Brolga', 'options': ['Canary', 'Merlin', 'Smew', 'Jabiru', 'Hamerkop', 'Greater Roadrunner']},
    {'level': 9, 'name': 'Smew', 'options': ['Willow Tit', 'Merlin', 'Bunting', 'Gannet', 'Shama', 'Dunlin']},
    {'level': 9, 'name': 'Kori Bustard', 'options': ['Gadwall', 'Merlin', 'Condor', 'Stork', 'Shama', 'Greater Roadrunner']},
    {'level': 9, 'name': 'Gannet', 'options': ['Brambling', 'King Quail', 'Bunting', 'Stork', 'Greater Roadrunner', 'Weka']},
    {'level': 9, 'name': 'Stork', 'options': ['Brambling', 'Canary', 'Jabiru', 'Jay', 'Heron', 'Cassowary']},
    {'level': 9, 'name': 'Kea', 'options': ['Willow Tit', 'Secretarybird', 'Jabiru', 'Stork', 'Heron', 'Dunlin']},
    {'level': 9, 'name': 'Jabiru', 'options': ['Canary', 'Brambling', 'Bunting', 'Kori Bustard', 'Hamerkop', 'Dunnock']},
    {'level': 9, 'name': 'Bunting', 'options': ['Teal', 'Merlin', 'Jay', 'Palmchat', 'Cassowary', 'Dunlin']},
    {'level': 9, 'name': 'Palmchat', 'options': ['Teal', 'Hawfinch', 'Gannet', 'Stork', 'Weka', 'Shama']},
    {'level': 10, 'name': 'Cassowary', 'options': ['Brambling', 'King Quail', 'Jay', 'Gannet', 'Heron', 'Bufflehead']},
    {'level': 10, 'name': 'Heron', 'options': ['Canary', 'Hawfinch', 'Kori Bustard', 'Gannet', 'Shama', 'Dunnock']},
    {'level': 10, 'name': 'Saddle-billed Stork', 'options': ['King Quail', 'Hawfinch', 'Gannet', 'Jabiru', 'Dunnock', 'Hamerkop']},
    {'level': 10, 'name': 'Weka', 'options': ['Canary', 'Gadwall', 'Jabiru', 'Palmchat', 'Bufflehead', 'Dunnock']},
    {'level': 10, 'name': 'Greater Roadrunner', 'options': ['Merlin', 'Willow Tit', 'Smew', 'Jay', 'Dunlin', 'Weka']},
    {'level': 10, 'name': 'Dunnock', 'options': ['King Quail', 'Willow Tit', 'Brolga', 'Condor', 'Saddle-billed Stork', 'Hamerkop']},
    {'level': 10, 'name': 'Shama', 'options': ['Merlin', 'Rhea', 'Bunting', 'Jay', 'Saddle-billed Stork', 'Dunnock']},
    {'level': 10, 'name': 'Bufflehead', 'options': ['Teal', 'Rhea', 'Kori Bustard', 'Bunting', 'Heron', 'Weka']},
    {'level': 10, 'name': 'Shikra', 'options': ['Teal', 'Canary', 'Stork', 'Gannet', 'Dunnock', 'Dunlin']},
    {'level': 10, 'name': 'Dunlin', 'options': ['Hawfinch', 'Willow Tit', 'Stork', 'Condor', 'Cassowary', 'Shama']},
    {'level': 10, 'name': 'Hamerkop', 'options': ['Merlin', 'Secretarybird', 'Condor', 'Bunting', 'Saddle-billed Stork', 'Greater Roadrunner']},
]

quiz = []

for bird in birds:
  bird['urls'] =  fetcher.fetch('bird', bird['name'])
  quiz.append(bird)

with open("output/birds.json", "w") as f:
    f.write(json.dumps(quiz))
