import fetcher


cities = [
    {'level': 1, 'name': 'London', 'options': ['Los Angeles', 'Paris', 'Kolkata', 'Madrid', 'Toronto', 'Melbourne']},
    {'level': 1, 'name': 'Paris', 'options': ['London', 'Moscow', 'Delhi', 'Mumbai', 'Washington D.C.', 'Mexico City']},
    {'level': 1, 'name': 'Rome', 'options': ['Paris', 'Sydney', 'Mumbai', 'Delhi', 'Mexico City', 'Athens']},
    {'level': 1, 'name': 'Sydney', 'options': ['Istanbul', 'Los Angeles', 'Tokyo', 'Mumbai', 'Dubai', 'Mexico City']},
    {'level': 1, 'name': 'New York', 'options': ['Paris', 'Los Angeles', 'Seattle', 'Agra', 'Rio de Janeiro', 'Dubai']},
    {'level': 1, 'name': 'San Francisco', 'options': ['Sydney', 'Los Angeles', 'Kolkata', 'Mumbai', 'Dubai', 'Toronto']},
    {'level': 1, 'name': 'Moscow', 'options': ['London', 'Sydney', 'Agra', 'Mumbai', 'Rio de Janeiro', 'Melbourne']},
    {'level': 1, 'name': 'Los Angeles', 'options': ['Rome', 'Sydney', 'Seattle', 'Delhi', 'Washington D.C.', 'Dubai']},
    {'level': 1, 'name': 'Istanbul', 'options': ['London', 'Sydney', 'Madrid', 'Delhi', 'Dubai', 'Melbourne']},
    {'level': 2, 'name': 'Mumbai', 'options': ['San Francisco', 'New York', 'Kolkata', 'Chicago', 'Melbourne', 'Mexico City']},
    {'level': 2, 'name': 'Chicago', 'options': ['New York', 'Sydney', 'Kolkata', 'Agra', 'Athens', 'Mexico City']},
    {'level': 2, 'name': 'Madrid', 'options': ['London', 'Los Angeles', 'Kolkata', 'Chicago', 'Mexico City', 'Toronto']},
    {'level': 2, 'name': 'Delhi', 'options': ['Istanbul', 'Los Angeles', 'Chicago', 'Tokyo', 'Toronto', 'Athens']},
    {'level': 2, 'name': 'Seattle', 'options': ['London', 'New York', 'Madrid', 'Delhi', 'Mexico City', 'Melbourne']},
    {'level': 2, 'name': 'Tokyo', 'options': ['Rome', 'Paris', 'Agra', 'Madrid', 'Washington D.C.', 'Mexico City']},
    {'level': 2, 'name': 'Agra', 'options': ['San Francisco', 'Los Angeles', 'Chicago', 'Tokyo', 'Mexico City', 'Melbourne']},
    {'level': 2, 'name': 'Kolkata', 'options': ['Paris', 'Los Angeles', 'Agra', 'Tokyo', 'Dubai', 'Athens']},
    {'level': 3, 'name': 'Rio de Janeiro', 'options': ['Tokyo', 'Madrid', 'Melbourne', 'Dubai', 'Munich', 'Amsterdam']},
    {'level': 3, 'name': 'Athens', 'options': ['Delhi', 'Madrid', 'Melbourne', 'Rio de Janeiro', 'Munich', 'Singapore']},
    {'level': 3, 'name': 'Washington D.C.', 'options': ['Chicago', 'Seattle', 'Dubai', 'Mexico City', 'Amsterdam', 'Kuala Lumpur']},
    {'level': 3, 'name': 'Dubai', 'options': ['Chicago', 'Agra', 'Rio de Janeiro', 'Toronto', 'Singapore', 'Amsterdam']},
    {'level': 3, 'name': 'Mexico City', 'options': ['Delhi', 'Kolkata', 'Rio de Janeiro', 'Athens', 'Giza', 'Kuala Lumpur']},
    {'level': 3, 'name': 'Melbourne', 'options': ['Kolkata', 'Chicago', 'Toronto', 'Mexico City', 'Munich', 'Singapore']},
    {'level': 3, 'name': 'Toronto', 'options': ['Tokyo', 'Mumbai', 'Athens', 'Mexico City', 'Singapore', 'Monaco']},
    {'level': 4, 'name': 'Monaco', 'options': ['Dubai', 'Melbourne', 'Munich', 'Pisa', 'Florence', 'Milan']},
    {'level': 4, 'name': 'Munich', 'options': ['Dubai', 'Washington D.C.', 'Pisa', 'Giza', 'Prague', 'Berlin']},
    {'level': 4, 'name': 'Pisa', 'options': ['Dubai', 'Rio de Janeiro', 'Singapore', 'Kuala Lumpur', 'Beijing', 'Saint Petersburg']},
    {'level': 4, 'name': 'Giza', 'options': ['Mexico City', 'Toronto', 'Singapore', 'Kuala Lumpur', 'Milan', 'Prague']},
    {'level': 4, 'name': 'Singapore', 'options': ['Dubai', 'Mexico City', 'Munich', 'Pisa', 'Milan', 'Berlin']},
    {'level': 4, 'name': 'Kuala Lumpur', 'options': ['Dubai', 'Melbourne', 'Monaco', 'Munich', 'Florence', 'Milan']},
    {'level': 4, 'name': 'Amsterdam', 'options': ['Melbourne', 'Toronto', 'Singapore', 'Giza', 'Jerusalem', 'Beijing']},
    {'level': 5, 'name': 'Prague', 'options': ['Kuala Lumpur', 'Singapore', 'Jerusalem', 'Saint Petersburg', 'Taipei City', 'Venice']},
    {'level': 5, 'name': 'Beijing', 'options': ['Munich', 'Kuala Lumpur', 'Florence', 'Saint Petersburg', 'Cairo', 'Taipei City']},
    {'level': 5, 'name': 'Berlin', 'options': ['Munich', 'Kuala Lumpur', 'Jerusalem', 'Prague', 'Venice', 'Vienna']},
    {'level': 5, 'name': 'Jerusalem', 'options': ['Giza', 'Kuala Lumpur', 'Beijing', 'Prague', 'Zurich', 'Lisbon']},
    {'level': 5, 'name': 'Saint Petersburg', 'options': ['Monaco', 'Pisa', 'Beijing', 'Berlin', 'Lisbon', 'Cairo']},
    {'level': 5, 'name': 'Florence', 'options': ['Monaco', 'Kuala Lumpur', 'Jerusalem', 'Milan', 'Taipei City', 'Lisbon']},
    {'level': 5, 'name': 'Milan', 'options': ['Amsterdam', 'Singapore', 'Florence', 'Berlin', 'Hong Kong', 'Taipei City']},
    {'level': 6, 'name': 'Lisbon', 'options': ['Florence', 'Beijing', 'Venice', 'Zurich', 'Amritsar', 'Srinagar']},
    {'level': 6, 'name': 'Hong Kong', 'options': ['Prague', 'Saint Petersburg', 'Lisbon', 'Venice', 'Varanasi', 'Srinagar']},
    {'level': 6, 'name': 'Venice', 'options': ['Milan', 'Jerusalem', 'Taipei City', 'Cairo', 'Bangkok', 'Varanasi']},
    {'level': 6, 'name': 'Cairo', 'options': ['Beijing', 'Milan', 'Vienna', 'Zurich', 'Shanghai', 'Seoul']},
    {'level': 6, 'name': 'Taipei City', 'options': ['Milan', 'Saint Petersburg', 'Zurich', 'Cairo', 'Bangkok', 'Srinagar']},
    {'level': 6, 'name': 'Zurich', 'options': ['Beijing', 'Milan', 'Vienna', 'Taipei City', 'Amritsar', 'Shanghai']},
    {'level': 6, 'name': 'Vienna', 'options': ['Saint Petersburg', 'Berlin', 'Venice', 'Taipei City', 'Seoul', 'Shanghai']},
    {'level': 7, 'name': 'Shanghai', 'options': ['Venice', 'Vienna', 'Srinagar', 'Amritsar', 'Buenos Aires', 'Budapest']},
    {'level': 7, 'name': 'Srinagar', 'options': ['Hong Kong', 'Cairo', 'Bangkok', 'Amritsar', 'Buenos Aires', 'Bangalore']},
    {'level': 7, 'name': 'Seoul', 'options': ['Zurich', 'Venice', 'Srinagar', 'Shanghai', 'Bangalore', 'Buenos Aires']},
    {'level': 7, 'name': 'Varanasi', 'options': ['Zurich', 'Lisbon', 'Shanghai', 'Seoul', 'Budapest', 'Buenos Aires']},
    {'level': 7, 'name': 'Bangkok', 'options': ['Cairo', 'Taipei City', 'Srinagar', 'Varanasi', 'Antalya', 'Chennai']},
    {'level': 7, 'name': 'Amritsar', 'options': ['Taipei City', 'Zurich', 'Seoul', 'Bangkok', 'Buenos Aires', 'Budapest']},
    {'level': 8, 'name': 'Bangalore', 'options': ['Amritsar', 'Shanghai', 'Budapest', 'Chennai', 'Copenhagen', 'Hanoi']},
    {'level': 8, 'name': 'Budapest', 'options': ['Amritsar', 'Seoul', 'Chennai', 'Bangalore', 'Madurai', 'Quito']},
    {'level': 8, 'name': 'Chennai', 'options': ['Varanasi', 'Seoul', 'Antalya', 'Buenos Aires', 'Hanoi', 'Chandigarh']},
    {'level': 8, 'name': 'Antalya', 'options': ['Amritsar', 'Seoul', 'Chennai', 'Bangalore', 'Quito', 'Hanoi']},
    {'level': 8, 'name': 'Buenos Aires', 'options': ['Amritsar', 'Srinagar', 'Chennai', 'Barcelona', 'Madurai', 'Copenhagen']},
    {'level': 8, 'name': 'Barcelona', 'options': ['Varanasi', 'Amritsar', 'Budapest', 'Chennai', 'Quito', 'Madurai']},
    {'level': 9, 'name': 'Osaka', 'options': ['Bangalore', 'Buenos Aires', 'Madurai', 'Hanoi', 'Kochi', 'Cape Town']},
    {'level': 9, 'name': 'Quito', 'options': ['Bangalore', 'Buenos Aires', 'Copenhagen', 'Madurai', 'Cape Town', 'Patna']},
    {'level': 9, 'name': 'Chandigarh', 'options': ['Budapest', 'Barcelona', 'Copenhagen', 'Madurai', 'Cape Town', 'Patna']},
    {'level': 9, 'name': 'Copenhagen', 'options': ['Barcelona', 'Buenos Aires', 'Hanoi', 'Quito', 'Porto', 'Dublin']},
    {'level': 9, 'name': 'Madurai', 'options': ['Buenos Aires', 'Antalya', 'Quito', 'Hanoi', 'Kochi', 'Cape Town']},
    {'level': 9, 'name': 'Hanoi', 'options': ['Barcelona', 'Buenos Aires', 'Chandigarh', 'Copenhagen', 'Dublin', 'Bhubaneswar']},
    {'level': 10, 'name': 'Dublin', 'options': ['Bangalore', 'Budapest', 'Madurai', 'Osaka', 'Bhubaneswar', 'Porto']},
    {'level': 10, 'name': 'Patna', 'options': ['Bangalore', 'Barcelona', 'Copenhagen', 'Madurai', 'Bhubaneswar', 'Kochi']},
    {'level': 10, 'name': 'Cape Town', 'options': ['Budapest', 'Buenos Aires', 'Quito', 'Hanoi', 'Patna', 'Dublin']},
    {'level': 10, 'name': 'Kochi', 'options': ['Antalya', 'Bangalore', 'Hanoi', 'Madurai', 'Bhubaneswar', 'Cape Town']},
    {'level': 10, 'name': 'Porto', 'options': ['Antalya', 'Budapest', 'Quito', 'Osaka', 'Patna', 'Bhubaneswar']},
    {'level': 10, 'name': 'Bhubaneswar', 'options': ['Chennai', 'Antalya', 'Osaka', 'Chandigarh', 'Patna', 'Kochi']},
]

quiz = []

for city in cities:
    curr = {}
    curr['options'] =  fetcher.fetch('city', city)
