import json

import fetcher


logos = [
    {'level': 1, 'name': 'Hyundai', 'options': ['Amazon', 'Chrome', 'Instagram', 'Skype', 'Monster', 'Ferrari']},
    {'level': 1, 'name': 'Mercedes', 'options': ['Toyota', 'Microsoft', 'Subway', 'Skype', 'Snapchat', 'uTorrent']},
    {'level': 1, 'name': 'Google', 'options': ['Mastercard', 'Microsoft', 'Red Bull', 'T-Mobile', 'YouTube', 'uTorrent']},
    {'level': 1, 'name': 'Parle-G', 'options': ['Hyundai', 'Audi', 'Tiktok', 'Ford', 'Cisco', 'Messenger']},
    {'level': 1, 'name': 'Facebook', 'options': ["McDonald's", 'Dominos', 'Starbucks', 'Suzuki', 'Firefox', 'uTorrent']},
    {'level': 1, 'name': 'Nike', 'options': ['Chrome', 'Hyundai', 'Ford', 'PhonePe', 'Porsche', 'Bing']},
    {'level': 1, 'name': 'Toyota', 'options': ['Parle-G', 'Chrome', 'PhonePe', 'Google Maps', 'Jaguar', 'Air Canada']},
    {'level': 1, 'name': 'LG', 'options': ['Google', 'Toyota', 'Pizza Hut', 'Tiktok', 'Monster', 'Snapchat']},
    {'level': 1, 'name': "McDonald's", 'options': ['Amazon', 'Nike', 'WhatsApp', 'Google Maps', 'Xbox', 'Air Canada']},
    {'level': 1, 'name': 'Dominos', 'options': ['Coca Cola', 'Mastercard', 'Adidas', 'Ford', 'Jaguar', 'Firefox']},
    {'level': 1, 'name': 'Chrome', 'options': ['Pepsi', 'Netflix', 'Red Bull', 'Skype', 'YouTube', 'Porsche']},
    {'level': 1, 'name': 'Honda', 'options': ['Hyundai', 'BMW', 'Wikipedia', 'T-Mobile', 'Bing', 'Microsoft Excel']},
    {'level': 1, 'name': 'BMW', 'options': ['Audi', 'KFC', 'Gmail', 'Motorola', 'Messenger', 'Microsoft Excel']},
    {'level': 1, 'name': 'Audi', 'options': ['Android', 'Netflix', 'Tesla', 'Instagram', 'Paypal', 'Skoda']},
    {'level': 1, 'name': 'Apple', 'options': ['BMW', 'Coca Cola', 'PhonePe', 'Instagram', 'Porsche', 'Air Canada']},
    {'level': 1, 'name': 'Amazon', 'options': ['Netflix', 'Google', 'Safari', 'Instagram', 'Monster', 'Nestle']},
    {'level': 1, 'name': 'Coca Cola', 'options': ['Microsoft', 'Mastercard', 'Instagram', 'Pizza Hut', 'Air Canada', 'Microsoft Excel']},
    {'level': 1, 'name': 'Netflix', 'options': ['Google', 'Microsoft', 'Red Bull', 'Dream11', 'Air Canada', 'Cisco']},
    {'level': 1, 'name': 'Microsoft', 'options': ['Parle-G', 'Google', 'Puma', 'Red Bull', 'Firefox', 'Microsoft Excel']},
    {'level': 1, 'name': 'Android', 'options': ['Dominos', 'Parle-G', 'DuckDuckGo', 'Wikipedia', 'Baskin Robbins', 'Cisco']},
    {'level': 1, 'name': 'Pepsi', 'options': ['Audi', 'Amazon', 'Suzuki', 'Tesla', 'Bing', 'Snapchat']},
    {'level': 1, 'name': 'KFC', 'options': ['Audi', 'Hyundai', 'Adobe', 'Tesla', 'Internet Explorer', 'YouTube']},
    {'level': 1, 'name': 'Mastercard', 'options': ['Android', 'Netflix', 'Suzuki', 'Puma', 'Cisco', 'Cash']},
    {'level': 2, 'name': 'Subway', 'options': ['Mercedes', 'Hyundai', 'Gmail', 'Adidas', 'Monster', 'Tinder']},
    {'level': 2, 'name': 'Red Bull', 'options': ['Nike', 'Mastercard', 'Instagram', 'Meta', 'Tinder', 'Mitsubishi']},
    {'level': 2, 'name': 'Gmail', 'options': ['Hyundai', 'Nike', 'PhonePe', 'Adidas', 'Bing', 'Messenger']},
    {'level': 2, 'name': 'Motorola', 'options': ['Chrome', 'Amazon', 'Ford', 'Safari', 'Ferrari', 'Firefox']},
    {'level': 2, 'name': 'Pizza Hut', 'options': ['Hyundai', 'Apple', 'T-Mobile', 'Suzuki', 'Porsche', 'Nestle']},
    {'level': 2, 'name': 'Safari', 'options': ['Honda', 'LG', 'Tiktok', 'DuckDuckGo', 'Monster', 'Cash']},
    {'level': 2, 'name': 'Adidas', 'options': ['Mastercard', 'Apple', 'Skype', 'Puma', 'Tinder', 'Messenger']},
    {'level': 2, 'name': 'DuckDuckGo', 'options': ['Android', 'Nike', 'Safari', 'Gmail', 'Xbox', 'Monster']},
    {'level': 2, 'name': 'T-Mobile', 'options': ['Parle-G', 'Mercedes', 'Starbucks', 'Google Maps', 'Air Canada', 'Xbox']},
    {'level': 2, 'name': 'Adobe', 'options': ['Android', 'Pepsi', 'Adidas', 'Subway', 'Firefox', 'Lipton']},
    {'level': 2, 'name': 'Chevrolet', 'options': ['Honda', 'KFC', 'Ford', 'Tiktok', 'Xbox', 'Monster']},
    {'level': 2, 'name': 'Instagram', 'options': ['BMW', 'Netflix', 'Microsoft Word', 'Starbucks', 'Warner Bros', 'Snapchat']},
    {'level': 2, 'name': 'Microsoft Word', 'options': ['Nike', 'Microsoft', 'Adobe', 'Tesla', 'Monster', 'Skoda']},
    {'level': 2, 'name': 'Meta', 'options': ['Nike', 'Facebook', 'Dream11', 'Red Bull', 'Monster', 'Lipton']},
    {'level': 2, 'name': 'Wikipedia', 'options': ['LG', 'Facebook', 'T-Mobile', 'Meta', 'Porsche', 'Firefox']},
    {'level': 2, 'name': 'Skype', 'options': ['Amazon', 'Chrome', 'Gmail', 'Pizza Hut', 'Xbox', 'Firefox']},
    {'level': 2, 'name': 'WhatsApp', 'options': ['Dominos', 'Apple', 'Dream11', 'Tesla', 'Cisco', 'Firefox']},
    {'level': 2, 'name': 'Dream11', 'options': ['Toyota', 'Amazon', 'Safari', 'WhatsApp', 'Tinder', 'Internet Explorer']},
    {'level': 2, 'name': 'Google Maps', 'options': ['Toyota', 'Chrome', 'PhonePe', 'Wikipedia', 'Firefox', 'Skoda']},
    {'level': 2, 'name': 'Puma', 'options': ['Honda', 'Nike', 'Chevrolet', 'Meta', 'YouTube', 'Porsche']},
    {'level': 2, 'name': 'Starbucks', 'options': ['Mastercard', 'LG', 'Skype', 'Red Bull', 'Cash', 'Xbox']},
    {'level': 2, 'name': 'Tiktok', 'options': ['Amazon', 'Nike', 'PhonePe', 'DuckDuckGo', 'Air Canada', 'Monster']},
    {'level': 2, 'name': 'Ford', 'options': ['Apple', 'Netflix', 'Meta', 'Instagram', 'Internet Explorer', 'Porsche']},
    {'level': 2, 'name': 'Tesla', 'options': ['Microsoft', 'Honda', 'PhonePe', 'Gmail', 'Tinder', 'uTorrent']},
    {'level': 2, 'name': 'Suzuki', 'options': ['BMW', 'Parle-G', 'Starbucks', 'Instagram', 'Baskin Robbins', 'Cisco']},
    {'level': 2, 'name': 'PhonePe', 'options': ['Mercedes', 'Netflix', 'Adobe', 'Adidas', 'Lipton', 'Porsche']},
    {'level': 3, 'name': 'Skoda', 'options': ['Pizza Hut', 'Google Maps', 'Lipton', 'YouTube', 'Google Photos', 'United Nations']},
    {'level': 3, 'name': 'uTorrent', 'options': ['Wikipedia', 'Red Bull', 'Porsche', 'Nestle', 'American Express', 'LinkedIn']},
    {'level': 3, 'name': 'Air Canada', 'options': ['Motorola', 'Chevrolet', 'Ferrari', 'Cash', 'Lexus', 'PlayStation']},
    {'level': 3, 'name': 'Snapchat', 'options': ['Microsoft Word', 'Tiktok', 'Air Canada', 'Internet Explorer', 'LinkedIn', 'PlayStation']},
    {'level': 3, 'name': 'Cisco', 'options': ['Skype', 'Dream11', 'Internet Explorer', 'Unilever', 'Vistara', 'UNICEF']},
    {'level': 3, 'name': 'Bing', 'options': ['Wikipedia', 'Instagram', 'Monster', 'Baskin Robbins', 'LinkedIn', 'UNICEF']},
    {'level': 3, 'name': 'Monster', 'options': ['Microsoft Word', 'Instagram', 'Baskin Robbins', 'Jaguar', 'Google Photos', 'New York Times']},
    {'level': 3, 'name': 'Firefox', 'options': ['Wikipedia', 'Adobe', 'Cisco', 'Snapchat', 'UNICEF', 'PlayStation']},
    {'level': 3, 'name': 'Tinder', 'options': ['Chevrolet', 'Tesla', 'Cash', 'Monster', 'Vistara', 'Google Photos']},
    {'level': 3, 'name': 'Porsche', 'options': ['Starbucks', 'Tesla', 'Messenger', 'uTorrent', 'Microsoft Outlook', 'LinkedIn']},
    {'level': 3, 'name': 'Nestle', 'options': ['Meta', 'Ford', 'Xbox', 'Air Canada', 'Broadcom', 'ING']},
    {'level': 3, 'name': 'Ferrari', 'options': ['Adidas', 'Starbucks', 'Internet Explorer', 'Paypal', 'Broadcom', "Levi's"]},
    {'level': 3, 'name': 'Messenger', 'options': ['T-Mobile', 'Skype', 'Porsche', 'Nestle', 'Wilson', 'Tommy Hilfiger']},
    {'level': 3, 'name': 'Xbox', 'options': ['Ford', 'DuckDuckGo', 'Microsoft Excel', 'uTorrent', 'Ikea', 'Microsoft Outlook']},
    {'level': 3, 'name': 'Cash', 'options': ['Red Bull', 'Wikipedia', 'Firefox', 'Unilever', 'Lays', 'American Express']},
    {'level': 3, 'name': 'Internet Explorer', 'options': ['Gmail', 'DuckDuckGo', 'Microsoft Excel', 'Paypal', 'Vistara', 'Microsoft Outlook']},
    {'level': 3, 'name': 'Jaguar', 'options': ['DuckDuckGo', 'Dream11', 'Nestle', 'Xbox', 'Bridgestone', 'Broadcom']},
    {'level': 3, 'name': 'Lipton', 'options': ['Starbucks', 'Motorola', 'Snapchat', 'Warner Bros', 'Lays', "Kellogg's"]},
    {'level': 3, 'name': 'Baskin Robbins', 'options': ['Wikipedia', 'Suzuki', 'Mitsubishi', 'Firefox', 'PlayStation', "Levi's"]},
    {'level': 3, 'name': 'Unilever', 'options': ['T-Mobile', 'Microsoft Word', 'Porsche', 'Cisco', "Levi's", 'Ikea']},
    {'level': 3, 'name': 'Paypal', 'options': ['PhonePe', 'Tiktok', 'Tinder', 'Microsoft Excel', 'Lays', 'Hilton']},
    {'level': 3, 'name': 'Mitsubishi', 'options': ['Motorola', 'Ford', 'Baskin Robbins', 'Microsoft Excel', 'Microsoft Outlook', 'American Express']},
    {'level': 3, 'name': 'YouTube', 'options': ['Pizza Hut', 'Chevrolet', 'Nestle', 'Bing', 'United Nations', 'Tommy Hilfiger']},
    {'level': 3, 'name': 'Microsoft Excel', 'options': ['Skype', 'Meta', 'Internet Explorer', 'Unilever', 'Ikea', 'LinkedIn']},
    {'level': 3, 'name': 'Warner Bros', 'options': ['Red Bull', 'Wikipedia', 'Tinder', 'Cash', 'Lays', 'United Nations']},
    {'level': 4, 'name': 'LinkedIn', 'options': ['Firefox', 'Paypal', 'Vistara', 'Lays', 'Lufthansa', 'Wordpress']},
    {'level': 4, 'name': 'PlayStation', 'options': ['Firefox', 'Baskin Robbins', 'UNICEF', "Kellogg's", 'Nvidia', 'Acura']},
    {'level': 4, 'name': 'Barclays', 'options': ['Lipton', 'uTorrent', 'Lexus', 'Hilton', 'Lacoste', 'Nvidia']},
    {'level': 4, 'name': 'Lays', 'options': ['Bing', 'uTorrent', 'Wilson', 'New York Times', 'Fiat', 'Lululemon']},
    {'level': 4, 'name': 'Broadcom', 'options': ['Lipton', 'Porsche', 'Hilton', 'Lexus', 'Discord', 'Lululemon']},
    {'level': 4, 'name': 'New York Times', 'options': ['Cash', 'Cisco', 'Hilton', 'LinkedIn', 'Wordpress', 'Samsonite']},
    {'level': 4, 'name': "Kellogg's", 'options': ['Baskin Robbins', 'Snapchat', 'UNICEF', 'Hilton', 'Volvo', 'Lacoste']},
    {'level': 4, 'name': 'Wilson', 'options': ['Firefox', 'Paypal', 'Barclays', 'Lays', 'Wordpress', 'Volvo']},
    {'level': 4, 'name': 'United Nations', 'options': ['Air Canada', 'Cisco', 'Lays', 'Lexus', 'Fiat', 'Michelin']},
    {'level': 4, 'name': 'Lexus', 'options': ['YouTube', 'Snapchat', 'UNICEF', 'PlayStation', 'Lufthansa', 'Fila']},
    {'level': 4, 'name': 'Google Photos', 'options': ['Unilever', 'Cisco', 'UNICEF', 'Ikea', 'Dove', 'Lacoste']},
    {'level': 4, 'name': 'Vistara', 'options': ['Snapchat', 'Porsche', 'Google Photos', 'Hilton', 'Volvo', 'Fruit of the Loom']},
    {'level': 4, 'name': 'Hilton', 'options': ['Skoda', 'Jaguar', "Kellogg's", 'Microsoft Outlook', 'Samsonite', 'Telegram']},
    {'level': 4, 'name': 'UNICEF', 'options': ['Cisco', 'Ferrari', "Levi's", 'LinkedIn', 'Telegram', 'Volvo']},
    {'level': 4, 'name': "Levi's", 'options': ['YouTube', 'Mitsubishi', 'Vistara', 'PlayStation', 'Michelin', 'British Airways']},
    {'level': 4, 'name': 'American Express', 'options': ['Ferrari', 'Tinder', 'Broadcom', 'Lays', 'Samsonite', 'Wordpress']},
    {'level': 4, 'name': 'Tommy Hilfiger', 'options': ['Mitsubishi', 'Warner Bros', 'American Express', 'UNICEF', 'Lacoste', 'Telegram']},
    {'level': 4, 'name': 'Microsoft Outlook', 'options': ['Tinder', 'Microsoft Excel', 'New York Times', 'PlayStation', 'Discord', 'Fruit of the Loom']},
    {'level': 4, 'name': 'Bridgestone', 'options': ['Tinder', 'YouTube', "Levi's", 'Vistara', 'Samsonite', 'Telegram']},
    {'level': 4, 'name': 'ING', 'options': ['Mitsubishi', 'Lipton', 'LinkedIn', 'Vistara', 'Fila', 'Bentley']},
    {'level': 4, 'name': 'Ikea', 'options': ['Mitsubishi', 'Tinder', 'United Nations', 'American Express', 'Fruit of the Loom', 'Lufthansa']},
    {'level': 5, 'name': 'Michelin', 'options': ['ING', 'Tommy Hilfiger', 'Wordpress', 'Bentley', 'Huawei', 'Corvette']},
    {'level': 5, 'name': 'British Airways', 'options': ['Vistara', 'ING', 'Louis Vuitton', 'Pinterest', 'Armani', 'Bacardi']},
    {'level': 5, 'name': 'Nvidia', 'options': ['New York Times', "Levi's", 'Louis Vuitton', 'Michelin', 'Evian', 'Bacardi']},
    {'level': 5, 'name': 'Dove', 'options': ['Hilton', 'Broadcom', 'Bentley', 'Pinterest', 'Chevron', 'Armani']},
    {'level': 5, 'name': 'Wordpress', 'options': ['Broadcom', 'Ikea', 'Discord', 'Lufthansa', 'Evian', 'Corvette']},
    {'level': 5, 'name': 'Lululemon', 'options': ['Google Photos', 'New York Times', 'Nvidia', 'Volvo', 'Armani', 'Texas Instruments']},
    {'level': 5, 'name': 'TripAdvisor', 'options': ['Wilson', 'Microsoft Outlook', 'Pinterest', 'Fila', 'Corvette', 'Evian']},
    {'level': 5, 'name': 'Telegram', 'options': ['Barclays', 'American Express', 'Dove', 'Lacoste', 'Chevron', 'Bacardi']},
    {'level': 5, 'name': 'Skechers', 'options': ['Tommy Hilfiger', 'UNICEF', 'Fila', 'Bentley', 'Eveready', 'Mustang']},
    {'level': 5, 'name': 'Lacoste', 'options': ['Tommy Hilfiger', 'American Express', 'Lufthansa', 'Pinterest', 'Chipotle', 'Under Armour']},
    {'level': 5, 'name': 'Pinterest', 'options': ['Barclays', 'Broadcom', 'Fila', 'Fruit of the Loom', 'Shell', 'Evian']},
    {'level': 5, 'name': 'Samsonite', 'options': ['Hilton', 'Microsoft Outlook', 'Lululemon', 'Louis Vuitton', 'Chipotle', 'Corvette']},
    {'level': 5, 'name': 'Fila', 'options': ['PlayStation', 'Wilson', 'Fiat', 'Lululemon', 'Evian', 'Bacardi']},
    {'level': 5, 'name': 'Fruit of the Loom', 'options': ['Bridgestone', 'Lexus', 'Fila', 'Acura', 'Swarovski', 'Pirelli']},
    {'level': 5, 'name': 'Louis Vuitton', 'options': ['UNICEF', "Levi's", 'Lululemon', 'Lacoste', 'Mustang', 'Under Armour']},
    {'level': 5, 'name': 'Bentley', 'options': ['Google Photos', 'Hilton', 'Telegram', 'Fruit of the Loom', 'Shell', 'Texas Instruments']},
    {'level': 5, 'name': 'Discord', 'options': ['American Express', 'Wilson', 'Fruit of the Loom', 'Telegram', 'Shell', 'Reddit']},
    {'level': 5, 'name': 'Lufthansa', 'options': ['Ikea', 'Lays', 'TripAdvisor', 'Dove', 'Shell', 'Emirates (airline)']},
    {'level': 5, 'name': 'Volvo', 'options': ['Broadcom', 'New York Times', 'Fiat', 'Nvidia', 'Huawei', 'Eveready']},
    {'level': 5, 'name': 'Acura', 'options': ['Broadcom', "Levi's", 'Fila', 'Nvidia', 'Under Armour', 'Swarovski']},
    {'level': 5, 'name': 'Fiat', 'options': ['LinkedIn', 'Barclays', 'Volvo', 'British Airways', 'Umbro', 'Shell']},
    {'level': 6, 'name': 'Chipotle', 'options': ['Lacoste', 'Acura', 'Opel', 'Mustang', 'Gatorade', 'John Deere']},
    {'level': 6, 'name': 'Eveready', 'options': ['Dove', 'Telegram', 'Reddit', 'Opel', 'Buick', 'American Airlines']},
    {'level': 6, 'name': 'Armani', 'options': ['Louis Vuitton', 'Nvidia', 'Emirates (airline)', 'Under Armour', 'Maserati', 'Buick']},
    {'level': 6, 'name': 'Shell', 'options': ['Wordpress', 'Lufthansa', 'Pirelli', 'Corvette', 'American Airlines', 'Maserati']},
    {'level': 6, 'name': 'Pringles', 'options': ['Volvo', 'Louis Vuitton', 'Emirates (airline)', 'Chipotle', 'Gatorade', 'Subaru']},
    {'level': 6, 'name': 'Pirelli', 'options': ['Fiat', 'Telegram', 'Swarovski', 'Opel', 'Buick', 'Monopoly']},
    {'level': 6, 'name': 'Reddit', 'options': ['Wordpress', 'Volvo', 'Swarovski', 'Mustang', 'Peugeot', 'Google Keep']},
    {'level': 6, 'name': 'Corvette', 'options': ['Volvo', 'Fruit of the Loom', 'Huawei', 'Reddit', 'Timberland', 'Buick']},
    {'level': 6, 'name': 'iTunes', 'options': ['Lululemon', 'Michelin', 'Armani', 'Texas Instruments', 'American Airlines', 'Walt Disney']},
    {'level': 6, 'name': 'Bacardi', 'options': ['Volvo', 'Nvidia', 'Reddit', 'Chevron', 'John Deere', 'Buick']},
    {'level': 6, 'name': 'Mustang', 'options': ['Samsonite', 'Lululemon', 'Bacardi', 'Reddit', 'Maserati', 'Peugeot']},
    {'level': 6, 'name': 'Swarovski', 'options': ['Wordpress', 'Telegram', 'Texas Instruments', 'Pirelli', 'Mazda', 'Gucci']},
    {'level': 6, 'name': 'Evian', 'options': ['Volvo', 'Fila', 'Armani', 'Eveready', 'Champion', 'American Airlines']},
    {'level': 6, 'name': 'Texas Instruments', 'options': ['Fila', 'Fiat', 'Mustang', 'Chevron', 'Champion', 'Maserati']},
    {'level': 6, 'name': 'Umbro', 'options': ['Pinterest', 'Michelin', 'Pringles', 'Huawei', 'Monopoly', 'Ralph Lauren']},
    {'level': 6, 'name': 'Opel', 'options': ['Lufthansa', 'Fruit of the Loom', 'Mustang', 'Arm & Hammer', 'Gucci', 'Buick']},
    {'level': 6, 'name': 'Chevron', 'options': ['Discord', 'Pinterest', 'Texas Instruments', 'Under Armour', 'Mazda', 'Google Keep']},
    {'level': 6, 'name': 'Huawei', 'options': ['Fruit of the Loom', 'TripAdvisor', 'Corvette', 'Bacardi', 'Champion', 'Buick']},
    {'level': 6, 'name': 'Arm & Hammer', 'options': ['Discord', 'Telegram', 'Eveready', 'Evian', 'Google Keep', 'Monopoly']},
    {'level': 6, 'name': 'Under Armour', 'options': ['Volvo', 'British Airways', 'Bacardi', 'Umbro', 'Google Keep', 'Peugeot']},
    {'level': 6, 'name': 'Emirates (airline)', 'options': ['Wordpress', 'Fruit of the Loom', 'Bacardi', 'Under Armour', 'Peugeot', 'Gatorade']},
    {'level': 7, 'name': 'Google Keep', 'options': ['Pirelli', 'Texas Instruments', 'American Airlines', 'Ralph Lauren', 'Turkish Airlines', 'Alfa Romeo']},
    {'level': 7, 'name': 'Champion', 'options': ['Arm & Hammer', 'Umbro', 'Ralph Lauren', 'SEAT', 'Qantas', 'Lincoln']},
    {'level': 7, 'name': 'Mazda', 'options': ['Chipotle', 'Pringles', 'Champion', 'SEAT', 'Air China', 'Turkish Airlines']},
    {'level': 7, 'name': 'Hawaiian Airlines', 'options': ['Opel', 'Texas Instruments', 'Gucci', 'Monopoly', "Dunkin' Donuts", 'Iberia (airline)']},
    {'level': 7, 'name': 'Timberland', 'options': ['Swarovski', 'Chipotle', 'Gatorade', 'Monopoly', 'Air China', 'Iberia (airline)']},
    {'level': 7, 'name': 'Gatorade', 'options': ['Bacardi', 'Corvette', 'Google Keep', 'SEAT', 'Brave', "Dunkin' Donuts"]},
    {'level': 7, 'name': 'Toblerone', 'options': ['Huawei', 'Eveready', 'Google Keep', 'APKPure', 'Duolingo', "Little Caesar's"]},
    {'level': 7, 'name': 'Ralph Lauren', 'options': ['Corvette', 'Chipotle', 'Gatorade', 'Walt Disney', 'Scion', 'Lincoln']},
    {'level': 7, 'name': 'American Airlines', 'options': ['Chevron', 'Under Armour', 'Mazda', 'Timberland', 'Scion', 'Iberia (airline)']},
    {'level': 7, 'name': 'Buick', 'options': ['Eveready', 'Evian', 'Champion', 'American Airlines', 'Alfa Romeo', 'Lincoln']},
    {'level': 7, 'name': 'APKPure', 'options': ['Corvette', 'Opel', 'Hawaiian Airlines', 'Mazda', 'Lincoln', 'Iberia (airline)']},
    {'level': 7, 'name': 'Gucci', 'options': ['Eveready', 'Pirelli', 'Peugeot', 'Hawaiian Airlines', 'Turkish Airlines', 'Duolingo']},
    {'level': 7, 'name': 'SEAT', 'options': ['Reddit', 'Mustang', 'Maserati', 'Mazda', "Little Caesar's", 'Cathay Pacific']},
    {'level': 7, 'name': 'Walt Disney', 'options': ['Eveready', 'Chipotle', 'Champion', 'APKPure', 'Turkish Airlines', "Dunkin' Donuts"]},
    {'level': 7, 'name': 'Peugeot', 'options': ['Texas Instruments', 'Opel', 'Toblerone', 'Maserati', 'Iberia (airline)', 'Citroën']},
    {'level': 7, 'name': 'Monopoly', 'options': ['Chevron', 'Chipotle', 'Google Keep', 'Subaru', 'Cathay Pacific', 'Rolex']},
    {'level': 7, 'name': 'Maserati', 'options': ['Mustang', 'Corvette', 'Gatorade', 'Buick', 'Brave', 'Citroën']},
    {'level': 7, 'name': 'John Deere', 'options': ['Arm & Hammer', 'Opel', 'Ralph Lauren', 'Peugeot', 'Citroën', 'Lincoln']},
    {'level': 7, 'name': 'Subaru', 'options': ['Under Armour', 'Bacardi', 'John Deere', 'Toblerone', 'Turkish Airlines', 'Qantas']},
    {'level': 8, 'name': 'Infiniti', 'options': ['Google Keep', 'APKPure', "Dunkin' Donuts", 'Lincoln', 'Dodge', 'Lemonheads']},
    {'level': 8, 'name': 'Cathay Pacific', 'options': ['John Deere', 'Maserati', 'Lincoln', "Dunkin' Donuts", 'Converse', 'Chanel']},
    {'level': 8, 'name': "Little Caesar's", 'options': ['Mazda', 'Gucci', 'Turkish Airlines', 'Rolex', 'Dodge', 'Converse']},
    {'level': 8, 'name': 'Alfa Romeo', 'options': ['Timberland', 'Mazda', "Little Caesar's", 'Brave', "Wendy's", 'Jelly Belly']},
    {'level': 8, 'name': 'Citroën', 'options': ['Google Keep', 'Maserati', 'Cathay Pacific', 'Air China', 'Caribbean Airlines', "Wendy's"]},
    {'level': 8, 'name': 'Rolex', 'options': ['Gucci', 'Monopoly', 'Citroën', 'Scion', 'Caribbean Airlines', 'Dreamworks']},
    {'level': 8, 'name': 'Duolingo', 'options': ['Peugeot', 'Maserati', 'Brave', "Dunkin' Donuts", 'Chanel', "Wendy's"]},
    {'level': 8, 'name': 'Air China', 'options': ['Ralph Lauren', 'Hawaiian Airlines', 'Rolex', 'Scion', 'Austrian Airlines', 'Gulf Air']},
    {'level': 8, 'name': 'Scion', 'options': ['Ralph Lauren', 'Subaru', 'Cathay Pacific', 'Turkish Airlines', "Wendy's", 'Mr. Clean']},
    {'level': 8, 'name': 'Qantas', 'options': ['Monopoly', 'Peugeot', 'Brave', 'Iberia (airline)', 'Southwest Airlines', 'Converse']},
    {'level': 8, 'name': 'Iberia (airline)', 'options': ['Ralph Lauren', 'Gucci', 'Citroën', 'Turkish Airlines', 'Mr. Clean', 'Lemonheads']},
    {'level': 8, 'name': 'Lincoln', 'options': ['APKPure', 'Google Keep', 'Air China', 'Turkish Airlines', 'Converse', 'Gulf Air']},
    {'level': 8, 'name': 'Brave', 'options': ['Monopoly', 'John Deere', 'Infiniti', 'Cathay Pacific', 'Jelly Belly', 'SriLankan Airlines']},
    {'level': 8, 'name': 'Turkish Airlines', 'options': ['Walt Disney', 'Monopoly', "Little Caesar's", 'Scion', 'Ryanair', 'Converse']},
    {'level': 8, 'name': "Dunkin' Donuts", 'options': ['Subaru', 'Walt Disney', 'Iberia (airline)', 'Brave', 'SriLankan Airlines', 'Chanel']},
    {'level': 9, 'name': 'Dreamworks', 'options': ['Duolingo', 'Alfa Romeo', 'Southwest Airlines', 'Dodge', 'BBM', 'WestJet']},
    {'level': 9, 'name': 'Lemonheads', 'options': ['Alfa Romeo', 'Qantas', 'Dreamworks', 'Southwest Airlines', 'Shutterstock', 'WestJet']},
    {'level': 9, 'name': 'Jelly Belly', 'options': ['Iberia (airline)', 'Duolingo', 'Southwest Airlines', 'Dodge', 'Häagen-Dazs', 'Qatar Airways']},
    {'level': 9, 'name': 'Austrian Airlines', 'options': ['Iberia (airline)', 'Infiniti', 'Caribbean Airlines', 'Jelly Belly', 'WestJet', 'Air Djibouti']},
    {'level': 9, 'name': 'Dodge', 'options': ["Little Caesar's", "Dunkin' Donuts", 'SriLankan Airlines', 'Southwest Airlines', 'Gerber', 'JD.com']},
    {'level': 9, 'name': 'Southwest Airlines', 'options': ['Turkish Airlines', 'Duolingo', 'Chanel', 'China Eastern Airlines', 'El Al', 'Air Albania']},
    {'level': 9, 'name': 'Mr. Clean', 'options': ['Air China', 'Cathay Pacific', 'Dodge', 'Lemonheads', 'Gerber', 'Qatar Airways']},
    {'level': 9, 'name': 'Converse', 'options': ['Duolingo', 'Cathay Pacific', 'Ryanair', 'Hermès', 'Aptoide', 'BBM']},
    {'level': 9, 'name': 'Chanel', 'options': ['Alfa Romeo', 'Iberia (airline)', 'Jelly Belly', 'Southwest Airlines', 'Azerbaijan Airlines', 'Air Burkina']},
    {'level': 9, 'name': 'Caribbean Airlines', 'options': ['Rolex', 'Air China', 'China Eastern Airlines', 'Austrian Airlines', 'Kangol', 'WestJet']},
    {'level': 9, 'name': "Wendy's", 'options': ['Cathay Pacific', 'Scion', 'Chanel', 'Jelly Belly', 'Air Albania', 'Air Djibouti']},
    {'level': 9, 'name': 'China Eastern Airlines', 'options': ['Brave', "Little Caesar's", 'Dodge', 'Chanel', 'Klondike', 'Gerber']},
    {'level': 9, 'name': 'Ryanair', 'options': ['Cathay Pacific', 'Qantas', 'China Eastern Airlines', 'Caribbean Airlines', 'Kangol', 'Air Djibouti']},
    {'level': 9, 'name': 'SriLankan Airlines', 'options': ['Duolingo', "Dunkin' Donuts", 'Chanel', 'Jelly Belly', 'China Southern Airlines', 'WestJet']},
    {'level': 9, 'name': 'Hermès', 'options': ['Infiniti', 'Cathay Pacific', 'Gulf Air', 'Jelly Belly', 'Aptoide', 'El Al']},
    {'level': 9, 'name': 'Gulf Air', 'options': ['Duolingo', 'Cathay Pacific', 'Jelly Belly', 'Austrian Airlines', 'Shutterstock', 'JD.com']},
    {'level': 10, 'name': 'Häagen-Dazs', 'options': ['Alfa Romeo', "Dunkin' Donuts", 'Gulf Air', "Wendy's", 'China Southern Airlines', 'Klondike']},
    {'level': 10, 'name': 'Klondike', 'options': ['Duolingo', 'Cathay Pacific', 'Caribbean Airlines', 'Hermès', 'Aptoide', 'Air Djibouti']},
    {'level': 10, 'name': 'Bic', 'options': ['Scion', 'Air China', 'Mr. Clean', 'Lemonheads', 'Kangol', 'Air Burkina']},
    {'level': 10, 'name': 'Azerbaijan Airlines', 'options': ['Qantas', 'Rolex', "Wendy's", 'Hermès', 'Air Albania', 'Chiquita']},
    {'level': 10, 'name': 'BBM', 'options': ['Scion', 'Infiniti', 'Caribbean Airlines', 'Gulf Air', 'Air Burkina', 'El Al']},
    {'level': 10, 'name': 'Aptoide', 'options': ["Little Caesar's", 'Citroën', 'Dodge', 'Lemonheads', 'Gerber', 'WestJet']},
    {'level': 10, 'name': 'El Al', 'options': ['Infiniti', 'Air China', 'Dreamworks', 'Caribbean Airlines', 'China Southern Airlines', 'WestJet']},
    {'level': 10, 'name': 'Air Burkina', 'options': ["Little Caesar's", "Dunkin' Donuts", "Wendy's", 'Dreamworks', 'BBM', 'JD.com']},
    {'level': 10, 'name': 'Shutterstock', 'options': ["Dunkin' Donuts", 'Alfa Romeo', 'Dodge', "Wendy's", 'Gerber', 'Air Algérie']},
    {'level': 10, 'name': 'WestJet', 'options': ['Citroën', "Dunkin' Donuts", 'Caribbean Airlines', 'Hermès', 'Klondike', 'Air Algérie']},
    {'level': 10, 'name': 'Air Algérie', 'options': ['Qantas', "Little Caesar's", 'Caribbean Airlines', 'Converse', 'Air Albania', 'Qatar Airways']},
    {'level': 10, 'name': 'Air Djibouti', 'options': ['Turkish Airlines', 'Iberia (airline)', 'Gulf Air', 'Lemonheads', 'Kangol', 'Gerber']},
    {'level': 10, 'name': 'Gerber', 'options': ['Scion', 'Lincoln', "Wendy's", 'Southwest Airlines', 'Air Burkina', 'El Al']},
    {'level': 10, 'name': 'Air Albania', 'options': ['Brave', 'Iberia (airline)', 'Dreamworks', 'Ryanair', 'China Southern Airlines', 'Air Burkina']},
    {'level': 10, 'name': 'Kangol', 'options': ['Infiniti', "Dunkin' Donuts", 'Converse', 'Dreamworks', 'Shutterstock', 'El Al']},
    {'level': 10, 'name': 'China Southern Airlines', 'options': ['Lincoln', "Dunkin' Donuts", 'Southwest Airlines', "Wendy's", 'Air Burkina', 'Häagen-Dazs']},
    {'level': 10, 'name': 'Chiquita', 'options': ['Alfa Romeo', 'Lincoln', 'Gulf Air', 'Austrian Airlines', 'Aptoide', 'Häagen-Dazs']},
    {'level': 10, 'name': 'JD.com', 'options': ['Citroën', 'Alfa Romeo', 'Lemonheads', 'Southwest Airlines', 'Air Burkina', 'Shutterstock']},
    {'level': 10, 'name': 'Qatar Airways', 'options': ['Alfa Romeo', 'Qantas', 'Caribbean Airlines', 'Gulf Air', 'Shutterstock', 'Air Burkina']}
]

quiz = []

for logo in logos:
    logo['urls'] =  fetcher.fetch('logo', logo['name'])
    quiz.append(logo)

with open("output/logos.json", "w") as f:
    f.write(json.dumps(quiz))
