import json
import time

import fetcher


people = [
  {'name': 'Mahatma Gandhi', 'options': ['Jawaharlal Nehru', 'Subhas Chandra Bose', 'Sardar Vallabhbhai Patel', 'Rabindranath Tagore', 'Ben Kingsley', 'Lala Lajpat Rai', 'Bal Gangadhar Tilak'], 'level': 1},
  {'name': 'Albert Enstein', 'options': ['Robert Oppenheimer', 'Nikola Tesla', 'Niels Bohr', 'Werner Heisenberg', 'Max Planck', 'Richard Feynman'], 'level': 1},
  {'name': 'Mother Teresa', 'options': ['Helen Keller', 'Aga Bojaxhiu', 'Florence Nightingale', 'Irmã Dulce', 'Rosa Parks', 'Dranafile Bojaxhiu'], 'level': 1},
  {'name': 'Nelson Mandela', 'options': ['Desmond Tutu', 'Thabo Mbeki', 'Oliver Tambo', 'Walter Sisulu', 'Jacob Zuma', 'Barack Obama'], 'level': 1},
  {'name': 'Winston Churchill', 'options': ['Neville Chamberlain', 'Joseph Stalin', 'Adolf Hitler', 'Franklin D. Roosevelt', 'Benito Mussolini', 'Nicholas Soames'], 'level': 1},
  {'name': 'William Shakespeare', 'options': ['Charles Dickens', 'Christopher Marlowe', 'Geoffrey Chaucer', 'Johannes Gutenberg', 'Niccolo Machiavelli', 'Leo Tolstoy'], 'level': 1},
  {'name': 'Adolf Hitler', 'options': ['Joseph Stalin', 'Benito Mussolini', 'Heinrich Himmler', 'Joseph Goebbels', 'Winston Churchill', 'Charlie Chaplin'], 'level': 1},
  {'name': 'John F. Kennedy', 'options': ['Lyndon B. Johnson', 'Robert Kennedy', 'Ted Kennedy', 'Dwight D. Eisenhower', 'Richard Nixon', 'Franklin D. Roosevelt'], 'level': 1},
  {'name': 'Princess Diana', 'options': ['Queen Camilla', 'Lady Sarah McCorquodale', 'Grace Kelly', 'Princess Margaret', 'Kate Middleton', 'Meghan Markle'], 'level': 1},
  {'name': 'Aishwarya Rai', 'options': ['Priyanka Chopra', 'Deepika Padukone', 'Madhuri Dixit', 'Kareena Kapoor', 'Anushka Sharma', 'Sushmita Sen'], 'level': 1},
  {'name': 'Charlie Chaplin', 'options': ['Buster Keaton', 'Adolf Hitler', 'Harold Lloyd', 'Jackie Coogan', 'James Thiérrée', 'Douglas Fairbanks'], 'level': 1},
  {'name': 'Tom Cruise', 'options': ['Brad Pitt', 'Val Kilmer', 'Harrison Ford', 'Tom Hanks', 'Johnny Depp', 'Russel Crowe'], 'level': 1},
  {'name': 'Michael Jackson', 'options': ['Bruno Mars', 'Nipsey Russell', 'Elvis Presley', 'Michael Jordan', 'Bruce Springsteen', 'Billy Joel'], 'level': 1},
  {'name': 'Donald Trump', 'options': ['Joe Biden', 'Barack Obama', 'Rudy Giuliani', 'Mike Pence', 'Chris Christie', 'Tucker Carlson'], 'level': 1},
  {'name': 'Vladimir Putin', 'options': ['Joe Biden', 'Alexander Lukashenko', 'Donald Trump', 'Xi Jinping', 'Dmitry Medvedev', 'Boris Yeltsin'], 'level': 1},
  {'name': 'Narendra Modi', 'options': ['Rahul Gandhi', 'Amit Shah', 'Yogi Adityanath', 'Manmohan Singh', 'Arvind Kejriwal', 'Nitin Gadkari', 'Nitish Kumar'], 'level': 1},
  {'name': 'Cristiano Ronaldo', 'options': ['Karim Benzema', 'Lionel Messi', 'Neymar', 'Kylian Mbappé', 'Erling Haaland', 'Zlatan Ibrahimović', 'Deco'], 'level': 1},
  {'name': 'Barack Obama', 'options': ['Joe Biden', 'Bill Clinton', 'Jimmy Carter', 'Ronald Reagan', 'Hunter Biden', 'Donald Trump'], 'level': 1},
  {'name': 'Indira Gandhi', 'options': ['Sonia Gandhi', 'Kamala Nehru', 'Priyanka Gandhi', 'Maneka Gandhi', 'Roopa Ganguly', 'Rabri Devi', 'Phoolan Devi'], 'level': 1},
  {'name': 'Hrithik Roshan', 'options': ['Tiger Shroff', 'Salman Khan', 'Abhishek Bachchan', 'Akshay Kumar', 'Farhan Akhtar', 'John Abraham', 'Ranbir Kapoor'], 'level': 1},
  {'name': 'David Beckham', 'options': ['Wayne Rooney', 'Zinedine Zidane', 'Ronaldinho', 'Ronaldo', 'Paul Scholes', 'Michael Owen', 'Alan Shearer'], 'level': 1},
  {'name': 'Osama Bin Laden', 'options': ['Ayman al-Zawahiri', 'Mohammed Atef', 'Saif al-Adel', 'Abdullah Yusuf Azzam', 'Abd Al-Rahman al-Nuaimi', 'Sayyid Qutb'], 'level': 1},
  {'name': 'MS Dhoni', 'options': ['Virat Kohli', 'Rohit Sharma', 'Ravindra Jadeja', 'Rahul Dravid', 'Yuvraj Singh', 'Sourav Ganguly'], 'level': 1},
  {'name': 'Issac Newton', 'options': ['Albert Einstein', 'Galileo Galilei', 'Johannes Kepler', 'Nicolaus Copernicus', 'René Descartes', 'Gottfried Wilhelm Leibniz', 'James Clerk Maxwell'], 'level': 1},
  {'name': 'Sachin Tendulkar', 'options': ['Virat Kohli', 'Virender Sehwag', 'Rahul Dravid', 'Sourav Ganguly', 'Vinod Kambli', 'VVS Laxman'], 'level': 1},
  {'name': 'Roger Federer', 'options': ['Andy Murray', 'Rafael Nadal', 'Novak Djokovic', 'Carlos Alcaraz', 'Pete Sampras', 'Stan Wawrinka', 'Andre Agassi', 'Daniil Medvedev', 'Andy Roddick'], 'level': 1},
  {'name': 'Lionel Messi', 'options': ['Robert Lewandowski', 'Harry Kane', 'Cristiano Ronaldo', 'Neymar', 'Mohamed Salah', 'Sergio Busquets', 'Luis Suárez', 'Jordi Alba', 'Andrés Iniesta'], 'level': 1},
  {'name': 'Satya Nadella', 'options': ['Sundar Pichai', 'Steve Ballmer', 'Shantanu Narayen', 'Parag Agrawal', 'Arvind Krishna', 'Ajay Banga', 'Rajeev Suri'], 'level': 1},
  {'name': 'Rafael Nadal', 'options': ['Andy Murray', 'Nick Kyrgios', 'Stefanos Tsitsipas', 'Alexander Zverev', 'Dominic Thiem', 'Casper Ruud', 'Gaël Monfils', 'Fernando Verdasco'], 'level': 1},
  {'name': 'Jawaharlal Nehru', 'options': ['Motilal Nehru', 'Subhas Chandra Bose', 'Feroze Gandhi', 'Lal Bahadur Shastri', 'Rajendra Prasad', 'Gulzarilal Nanda'], 'level': 1},
  {'name': 'Stephen Hawking', 'options': ['Albert Einstein', 'Isaac Newton', 'Nikola Tesla', 'Richard Feynman', 'Roger Penrose', 'Robert Oppenheimer', 'Thomas Hertog', 'Kip Thorne'], 'level': 1},
  {'name': 'Aamir Khan', 'options': ['Salman Khan', 'Shah Rukh Khan', 'Akshay Kumar', 'Faisal Khan', 'Saif Ali Khan', 'R. Madhavan', 'Sharman Joshi'], 'level': 2},
  {'name': 'Abraham Lincoln', 'options': ['George Washington', 'Andrew Johnson', 'John Wilkes Booth', 'Ulysses S. Grant', 'Thomas Jefferson', 'James Buchanan', 'Jefferson Davis'], 'level': 2},
  {'name': 'Angelina Jolie', 'options': ['Jennifer Aniston', 'Megan Fox', 'Jennifer Lopez', 'Scarlett Johansson', 'Winona Ryder', 'Charlize Theron', 'Adriana Lima'], 'level': 2},
  {'name': 'Maria Sharapova', 'options': ['Anna Kournikova', 'Caroline Wozniacki', 'Ana Ivanović', 'Martina Hingis', 'Steffi Graf', 'Martina Navratilova', 'Justine Henin', 'Monica Seles'], 'level': 2},
  {'name': 'Shah Rukh Khan', 'options': ['Salman Khan', 'Aamir Khan', 'Akshay Kumar', 'Ajay Devgn', 'Saif Ali Khan', 'Suniel Shetty', 'Anil Kapoor', 'Bobby Deol'], 'level': 2},
  {'name': 'Virat Kohli', 'options': ['Rohit Sharma', 'KL Rahul', 'Shubman Gill', 'Hardik Pandya', 'Ravindra Jadeja', 'Ishan Kishan', 'Ravichandran Ashwin', 'Shikhar Dhawan'], 'level': 2},
  {'name': 'Frank Lampard', 'options': ['Steven Gerrard', 'Didier Drogba', 'Wayne Rooney', 'Ashley Cole', 'Joe Cole', 'Petr Čech', 'Michael Essien'], 'level': 2},
  {'name': 'Ernesto Che Guevara', 'options': ['Fidel Castro', 'Fulgencio Batista', 'Karl Marx', 'Hugo Chávez', 'Leon Trotsky', 'Mario Terán', 'Malcolm X'], 'level': 2},
  {'name': 'Kim Jong Un', 'options': ['Xi Jinping', 'Kim Tok-hun', 'Jang Song-thaek', 'Moon Jae-in', 'Yoon Suk Yeol', 'Kim Jong-il', 'Kim Il-sung'], 'level': 2},
  {'name': 'Martin Luther King Jr.', 'options': ['Nelson Mandela', 'Dexter King', 'Bayard Rustin', 'Jesse Jackson', 'Lyndon B. Johnson', 'A. Philip Randolph', 'Ralph Abernathy'], 'level': 2},
  {'name': 'Queen Elizabeth II', 'options': ['Princess Margaret', 'Anne, Princess Royal', 'Queen Camilla', 'Queen Victoria', 'Princess Beatrice', 'Margaret Thatcher'], 'level': 2},
  {'name': 'Jackie Chan', 'options': ['Bruce Lee', 'Chris Tucker', 'Jet Li', 'John Cena', 'Sammo Hung', 'Chuck Norris', 'Sylvester Stallone', 'Stephen Chow'], 'level': 2},
  {'name': 'Kate Winslet', 'options': ['Saoirse Ronan', 'Cate Blanchett', 'Emma Thompson', 'Emma Watson', 'Lashana Lynch', 'Keira Knightley', 'Kristen Stewart', 'Kirsten Dunst'], 'level': 2},
  {'name': 'Daniel Craig', 'options': ['Pierce Brosnan', 'Sean Connery', 'Timothy Dalton', 'Henry Cavill', 'Idris Elba', 'Mads Mikkelsen', 'Brad Pitt', 'Tom Cruise'], 'level': 2},
  {'name': 'Dalai Lama', 'options': ['Thich Nhat Hanh', 'Pema Chödrön', 'Rahul Sankrityayan', 'Jack Kornfield', 'Dudjom Jigdral Yeshe Dorje', 'Jampa Tegchok'], 'level': 2},
  {'name': 'Pele', 'options': ['Ronaldo', 'Garrincha', 'Dondinho', 'Jairzinho', 'Mário Zagallo', 'Rivellino', 'Zico', 'Nílton Santos', 'Didi', 'Sócrates', 'Eusébio'], 'level': 2},
  {'name': 'Amitabh Bachchan', 'options': ['Dharmendra', 'Rajinikanth', 'Kamal Haasan', 'Rishi Kapoor', 'Randhir Kapoor', 'Shashi Kapoor', 'Rajesh Khanna'], 'level': 2},
  {'name': 'Kalpana Chawla', 'options': ['Sunita Williams', 'Sirisha Bandla', 'Laurel Clark', 'Kamala Sohonie', 'Geetanjali Shree', 'Beth Moses'], 'level': 2},
  {'name': 'Mukesh Ambani', 'options': ['Anil Ambani', 'Dhirubhai Ambani', 'Gautam Adani', 'Ratan Tata', 'Lakshmi Mittal', 'Anand Mahindra'], 'level': 2},
  {'name': 'Michael Schumacher', 'options': ['Alain Prost', 'Mika Häkkinen', 'Damon Hill', 'Jacques Villeneuve', 'Nigel Mansell', 'Rubens Barrichello'], 'level': 2},
  {'name': 'Sundar Pichai', 'options': ['Satya Nadella', 'Shantanu Narayen', 'Parag Agrawal', 'Jay Chaudhry', 'Dinesh Paliwal', 'Neal Mohan'], 'level': 2},
  {'name': 'Tiger Woods', 'options': ['Rory McIlroy', 'Phil Mickelson', 'Jack Nicklaus', 'Rickie Fowler', 'Scottie Scheffler', 'Ernie Els', 'Vijay Singh'], 'level': 2},
  {'name': 'Mark Zuckerberg', 'options': ['Eduardo Saverin', 'Elon Musk', 'Tim Cook', 'Tyler Winklevoss', 'Andrew Bosworth', 'Chris Hughes'], 'level': 2},
  {'name': 'Leonardo DiCaprio', 'options': ['Brad Pitt', 'Billy Zane', 'Johnny Depp', 'Tobey Maguire', 'George Clooney', 'Matt Damon', 'Ben Affleck', 'Cillian Murphy'], 'level': 2},
  {'name': 'Joseph Stalin', 'options': ['Vladimir Lenin', 'Nikita Khrushchev', 'Winston Churchill', 'Karl Marx', 'Mikhail Gorbachev', 'Georgy Zhukov', 'Harry S. Truman'], 'level': 3},
  {'name': 'Marilyn Monroe', 'options': ['Audrey Hepburn', 'Elizabeth Taylor', 'Katharine Hepburn', 'Grace Kelly', 'Mary Pickford', 'Vivien Leigh', 'Ava Gardner'], 'level': 3},
  {'name': 'John Lennon', 'options': ['George Harrison', 'Ringo Starr', 'Pete Best', 'John Legend', 'Elvis Presley', 'Mick Jagger', 'Bob Dylan', 'Elton John'], 'level': 3},
  {'name': 'Johnny Depp', 'options': ['Orlando Bloom', 'Tom Cruise', 'Keanu Reeves', 'Robert Downey Jr.', 'Cillian Murphy', 'Chris Hemsworth', 'Tom Holland'], 'level': 3},
  {'name': 'LeBron James', 'options': ['Stephen Curry', 'Michael Jordan', 'Kobe Bryant', 'Kevin Durant', "Shaquille O'Neal", 'Kareem Abdul-Jabbar'], 'level': 3},
  {'name': 'Oprah Winfrey', 'options': ['Michelle Obama', 'Ellen DeGeneres', 'Beyonce', 'Jennifer Lopez', 'Rihanna', 'Nicki Minaj'], 'level': 3},
  {'name': 'John Terry', 'options': ['Rio Ferdinand', 'Gary Cahill', 'Ricardo Carvalho', 'Paulo Ferreira', 'Alex', 'Nemanja Vidić'], 'level': 3},
  {'name': 'Neil Armstrong', 'options': ['Buzz Aldrin', 'Michael Collins', 'Yuri Gagarin', 'David R.Scott', 'Gene Cernan'], 'level': 3},
  {'name': 'Charles Darwin', 'options': ['Alfred Russel Wallace', 'Gregor Mendel', 'Sigmund Freud', 'Herbert Spencer', 'Louis Pasteur'], 'level': 3},
  {'name': 'Michael Jordan', 'options': ['Kobe Bryant', "Shaquille O'Neal", 'Magic Johnson', 'Stephen Curry', 'Kevin Durant', 'Bill Russell', 'Wilt Chamberlain'], 'level': 3},
  {'name': 'Steve Jobs', 'options': ['Tim Cook', 'Steve Wozniak', 'Mark Zuckerberg', 'Bill Gates', 'Warren Buffett', 'Larry Page', 'Larry Ellison'], 'level': 3},
  {'name': 'Bruce Lee', 'options': ['Jackie Chan', 'Chuck Norris', 'Bruce Willis', 'Muhammad Ali', 'Jet Li', 'Vidyut Jammwal'], 'level': 3},
  {'name': 'Kim Kardashian', 'options': ['Kylie Jenner', 'Paris Hilton', 'Jennifer Lopez', 'Ariana Grande', 'Britney Spears', 'Selena Gomez'], 'level': 3},
  {'name': 'Rajendra Prasad', 'options': ['Sarvepalli Radhakrishnan', 'Jawaharlal Nehru', 'Zakir Husain', 'C. Rajagopalachari', 'V. V. Giri', 'Fakhruddin Ali Ahmed'], 'level': 3},
  {'name': 'Taylor Swift', 'options': ['Selena Gomez', 'Ariana Grande', 'Olivia Rodrigo', 'Katy Perry', 'Miley Cyrus', 'Dua Lipa'], 'level': 3},
  {'name': 'Sunil Chhetri', 'options': ['Bhaichung Bhutia', 'Gurpreet Singh Sandhu', 'Sandesh Jhingan', 'Lallianzuala Chhangte', 'Udanta Singh Kumam', 'Anirudh Thapa'], 'level': 3},
  {'name': 'José Mourinho', 'options': ['Pep Guardiola', 'Carlo Ancelotti', 'Alex Ferguson', 'Antonio Conte', 'Mauricio Pochettino', 'Thomas Tuchel'], 'level': 3},
  {'name': 'Bill Gates', 'options': ['Jeff Bezos', 'Steve Jobs', 'Warren Buffett', 'Paul Allen', 'Bernard Arnault', 'Tim Cook'], 'level': 3},
  {'name': 'Gary Kirsten', 'options': ['John Wright', 'Herschelle Gibbs', 'Jonty Rhodes', 'Daryll Cullinan', 'Lance Klusener', 'Andrew Hudson'], 'level': 3},
  {'name': 'Harmanpreet Kaur', 'options': ['Smriti Mandhana', 'Mithali Raj', 'Jemimah Rodrigues', 'Deepti Sharma', 'Shafali Verma', 'Harleen Deol'], 'level': 3},
  {'name': 'Margot Robbie', 'options': ['Emma Mackey', 'Greta Gerwig', 'Emma Stone', 'Eva Mendes', 'Cara Delevingne', 'Gal Gadot'], 'level': 3},
  {'name': 'Rowan Atkinson', 'options': ['Hugh Grant', 'Hugh Laurie', 'Stephen Fry', 'John Cleese'], 'level': 3},
  {'name': 'Vladimir Lenin', 'options': ['Joseph Stalin', 'Karl Marx', 'Grigori Rasputin', 'Mikhail Gorbachev', 'Nikita Khrushchev'], 'level': 4},
  {'name': 'Muhammad Ali', 'options': ['Mike Tyson', 'George Foreman', 'Joe Frazier', 'Floyd Mayweather Jr.', 'Joe Louis', 'Sonny Liston'], 'level': 4},
  {'name': 'J.K.Rowling', 'options': ['Bonnie Wright', 'Evanna Lynch', 'Helena Bonham Carter', 'Maggie Smith', 'Emma Watson'], 'level': 4},
  {'name': 'Greta Thunberg', 'options': ['Naomi Seibt', 'Luisa-Marie Neubauer', 'Carla Hinrichs', 'Vanessa Nakate'], 'level': 4},
  {'name': 'Dhyan Chand', 'options': ['Roop Singh', 'Milkha Singh', 'Neeraj Chopra', 'Balbir Singh Sr.', 'Udham Singh'], 'level': 4},
  {'name': 'Ed Sheeran', 'options': ['Lewis Capaldi', 'Justin Bieber', 'Bruno Mars', 'Harry Styles', 'Eminem', 'James Arthur'], 'level': 4},
  {'name': 'Carlo Ancelotti', 'options': ['Zinedine Zidane', 'Jürgen Klopp', 'Antonio Conte', 'Rafael Benítez', 'Luiz Felipe Scolari', 'Luciano Spalletti'], 'level': 4},
  {'name': 'Salman Rushdie', 'options': ['V.S. Naipaul', 'Kazuo Ishiguro', 'Stephen King', 'Amitav Ghosh', 'Aravind Adiga', 'Amish Tripathi', 'Ruskin Bond'], 'level': 4},
  {'name': 'Yasser Arafat', 'options': ['Mahmoud Abbas', 'Muammar Gaddafi', 'Ehud Barak', 'Saddam Hussein', 'Nabil Shaath', 'Ahmed Qurei'], 'level': 4},
  {'name': 'Kimi Räikkönen', 'options': ['Sebastian Vettel', 'Fernando Alonso', 'Valtteri Bottas', 'Mika Häkkinen', 'Nico Rosberg', 'David Coulthard'], 'level': 4},
  {'name': 'Francis Ford Coppola', 'options': ['Martin Scorsese', 'Mario Puzo', 'Marlon Brando', 'Al Pacino', 'Robert De Niro', 'James Caan'], 'level': 4},
  {'name': 'Paul McCartney', 'options': ['Ringo Starr', 'George Harrison', 'Mick Jagger', 'Eric Clapton', 'Keith Richards', 'Bruce Springsteen', 'Bob Dylan'], 'level': 4},
  {'name': 'Thiago Silva', 'options': ['Marquinhos', 'David Luiz', 'Dani Alves', 'César Azpilicueta', 'Alex Sandro', 'Axel Disasi'], 'level': 4},
  {'name': 'Viswanathan Anand', 'options': ['Rameshbabu Praggnanandhaa', 'Hikaru Nakamura', 'Garry Kasparov', 'Gukesh D', 'Veselin Topalov', 'Anish Giri'], 'level': 4},
  {'name': 'Lisa Ray', 'options': ['Sheetal Sheth', 'Lisa Haydon', 'Nargis Fakhri', "Ileana D'Cruz", 'Hazel Keech', 'Nataša Stanković'], 'level': 4},
  {'name': 'Serena Williams', 'options': ['Venus Williams', 'Naomi Osaka', 'Coco Gauff', 'Simona Halep', 'Sloane Stephens', 'Caroline Wozniacki'], 'level': 4},
  {'name': 'Rihanna', 'options': ['Beyonce', 'Nicki Minaj', 'Shakira', 'Cardi B', 'Lady Gaga', 'Mariah Carey', 'Adele'], 'level': 4},
  {'name': 'Ravi Shankar', 'options': ['Zakir Hussain', 'Ali Akbar Khan', 'Hariprasad Chaurasia', 'Alla Rakha', 'Bismillah Khan', 'Vilayat Khan'], 'level': 4},
  {'name': 'Rami Malek', 'options': ['Robert Downey Jr.', 'Cillian Murphy', 'Ben Hardy', 'Paul Anderson', 'Jack Quaid', 'Ryan Gosling'], 'level': 4},
  {'name': 'Elon Musk', 'options': ['Jeff Bezos', 'Mark Zuckerberg', 'Donald Trump', 'Warren Buffett', 'Larry Page'], 'level': 4},
  {'name': 'Mao Zedong', 'options': ['Deng Xiaoping', 'Xi Jinping', 'Jiang Zemin', 'Hu Jintao', 'Liu Shaoqi'], 'level': 5},
  {'name': 'Elvis Presley', 'options': ['Frank Sinatra', 'Johnny Cash', 'Chuck Berry', 'Elton John', 'Buddy Holly', 'Michael Jackson'], 'level': 5},
  {'name': 'Barkha Dutt', 'options': ['Sagarika Ghose', 'Nidhi Razdan', 'Rana Ayyub', 'Swati Chaturvedi', 'Sweta Singh'], 'level': 5},
  {'name': 'Ellen Degeneres', 'options': ["Rosie O'Donnell", 'Katy Perry', 'Britney Spears', 'Anne Heche', 'Portia de Rossi'], 'level': 5},
  {'name': 'Alfred Hitchcock', 'options': ['Martin Scorsese', 'Steven Spielberg', 'David Lean', 'Noël Coward', 'Sam Spiegel'], 'level': 5},
  {'name': 'Benazir Bhutto', 'options': ['Indira Gandhi', 'Dina Wadia', 'Sheikh Hasina', 'Sirimavo Bandaranaike', 'Chandrika Kumaratunga'], 'level': 5},
  {'name': 'Mikhail Gorbachev', 'options': ['Boris Yeltsin', 'Nikita Khrushchev', 'Joseph Stalin', 'Georgy Malenkov', 'Konstantin Chernenko', 'Yuri Andropov'], 'level': 5},
  {'name': 'Freddie Mercury', 'options': ['Brian May', 'Roger Taylor', 'John Deacon', 'David Bowie', 'George Michael', 'Kurt Cobain'], 'level': 5},
  {'name': 'Jack Ma', 'options': ['Ma Huateng', 'Robin Li', 'Zhang Yiming', 'Masayoshi Son'], 'level': 5},
  {'name': 'Kabir Bedi', 'options': ['Louis Jourdan', 'Michael Gregg Wilson', 'Adolfo Celi', 'Tom Alter', 'Bob Christo'], 'level': 5},
  {'name': 'Jeff Bezos', 'options': ['Elon Musk', 'Bernard Arnault', 'Warren Buffett', 'Andy Jassy', 'Larry Ellison', 'Richard Branson'], 'level': 5},
  {'name': 'Homi J. Bhabha', 'options': ['Vikram Sarabhai', 'C. V. Raman', 'A. P. J. Abdul Kalam', 'Satish Dhawan', 'Nambi Narayanan', 'Subrahmanyan Chandrasekhar'], 'level': 5},
  {'name': 'Trevor Noah', 'options': ['Jon Stewart', 'Stephen Colbert', 'Hasan Minhaj', 'Roy Wood Jr.', 'Chris Rock', 'Dave Chappelle'], 'level': 5},
  {'name': 'Annabelle Wallis', 'options': ['Sofia Boutella', 'Sophie Rundle', "Natasha O'Keeffe", 'Vera Farmiga', 'Anna Kendrick'], 'level': 5},
  {'name': 'P. T. Usha', 'options': ['Hima Das', 'PV Sindhu', 'Mary Kom', 'Karnam Malleswari', 'Anju Bobby George', 'Saina Nehwal', 'Geeta Phogat'], 'level': 5},
  {'name': 'Ayrton Senna', 'options': ['Alain Prost', 'Nigel Mansell', 'Nelson Piquet', 'Niki Lauda', 'Roland Ratzenberger', 'James Hunt'], 'level': 5},
  {'name': 'Harry Styles', 'options': ['Zayn Malik', 'Justin Bieber', 'Ed Sheeran', 'Niall Horan', 'Louis Tomlinson', 'Liam Payne'], 'level': 5},
  {'name': 'Marie Curie', 'options': ['Rosalind Franklin', 'Lise Meitner', 'Augusta Ada Lovelace', 'Bronisława Dłuska'], 'level': 5},
  {'name': 'Sam Kerr', 'options': ['Ellie Carpenter', 'Guro Reiten', 'Fran Kirby', 'Jess Carter', 'Millie Bright', 'Lauren James'], 'level': 6},
  {'name': 'John Travolta', 'options': ['Quentin Tarantino', 'Bruce Willis', 'Nicolas Cage', 'Arnold Schwarzenegger', 'Mel Gibson'], 'level': 6},
  {'name': 'Nambi Narayanan', 'options': ['Vikram Sarabhai', 'Satish Dhawan', 'A. P. J. Abdul Kalam', 'C. V. Raman', 'Subbiah Arunan'], 'level': 6},
  {'name': 'Roger Moore', 'options': ['Timothy Dalton', 'Pierce Brosnan', 'Sean Connery', 'Desmond Llewelyn', 'Christopher Lee'], 'level': 6},
  {'name': 'Ingrid Bergman', 'options': ['Isabella Rossellini', 'Katharine Hepburn', 'Grace Kelly', 'Audrey Hepburn', 'Marilyn Monroe'], 'level': 6},
  {'name': 'Vijay Amritraj', 'options': ['Ramesh Krishnan', 'Ramanathan Krishnan', 'Mahesh Bhupathi', 'Rohan Bopanna', 'Leander Paes', 'Prakash Padukone'], 'level': 6},
  {'name': 'Megyn Kelly', 'options': ['Gretchen Carlson', 'Elizabeth Vargas', 'Robin Roberts', 'Fredricka Whitfield', 'Christiane Amanpour', 'Shereen Bhan'], 'level': 6},
  {'name': 'Lauren James', 'options': ['Guro Reiten', 'Erin Cuthbert', 'Jessie Fleming', 'Melanie Leupolz', 'Niamh Charles', 'Sophie Ingle'], 'level': 6},
  {'name': 'Larry Page', 'options': ['Sergey Brin', 'Carlos Slim', 'Tim Cook', 'Jeff Bezos', 'Eric Schmidt'], 'level': 6},
  {'name': 'Kofi Annan', 'options': ['Ban Ki-moon', 'Boutros Ghali', 'U Thant', 'Trygve Lie', 'Nelson Mandela', 'Kurt Waldheim'], 'level': 6},
  {'name': 'Marat Safin', 'options': ['Lleyton Hewitt', 'Andy Roddick', 'Pat Rafter', 'Gustavo Kuerten', 'Juan Martín del Potro', 'David Nalbandian'], 'level': 6},
  {'name': 'Charles Babbage', 'options': ['Alan Turing', 'Blaise Pascal', 'George Boole', 'John von Neumann', 'John Napier', 'Gottfried Wilhelm Leibniz'], 'level': 6},
  {'name': 'Gianni Infantino', 'options': ['Sepp Blatter', 'Aleksander Čeferin', 'Michel Platini', 'Luis Rubiales', 'Alejandro Dominguez', 'Pierluigi Collina'], 'level': 6},
  {'name': 'Ellyse Perry', 'options': ['Alyssa Healy', 'Meg Lanning', 'Ashleigh Gardner', 'Heather Knight', 'Sophie Devine', 'Danni Wyatt'], 'level': 6},
  {'name': 'Michelle Yeoh', 'options': ['Gemma Chan', 'Zhang Ziyi', 'Gong Li', 'Kelly Reilly', 'Isabella Leong', 'Oona Chaplin', 'Paula Malai Ali'], 'level': 6},
  {'name': 'John Oliver', 'options': ['Jon Stewart', 'Stephen Colbert', 'Seth Meyers', 'Bill Maher', 'David Letterman', 'Jimmy Fallon', 'Jimmy Kimmel'], 'level': 6},
  {'name': 'Jennifer Hermoso', 'options': ['Alexia Putellas', 'Olga Carmona', 'Ona Batlle', 'Lucy Bronze', 'Ann-Katrin Berger', 'Zećira Mušović'], 'level': 6},
  {'name': 'Kurt Angle', 'options': ['Chris Jericho', 'Triple H', 'Brock Lesnar', 'Shawn Michaels', 'John Cena', 'Hulk Hogan', 'The Undertaker'], 'level': 6},
  {'name': 'David Gilmour', 'options': ['Roger Waters', 'Syd Barrett', 'Richard Wright', 'Nick Mason', 'David Bowie', 'Bob Klose'], 'level': 6},
  {'name': 'Malala Yousafzai', 'options': ['Nadia Murad', 'Wangari Maathai', 'Maria da Penha', 'Mahira Khan', 'Sana Mir', 'Fatima Bhutto'], 'level': 7},
  {'name': 'Elton John', 'options': ['Billy Joel', 'George Michael', 'Mick Jagger', 'David Bowie', 'Eric Clapton', 'Billy Idol'], 'level': 7},
  {'name': 'Wilt Chamberlain', 'options': ['Kareem Abdul-Jabbar', 'Magic Johnson', "Shaquille O'Neal", 'Kobe Bryant', 'Stephen Curry', 'John Havlicek'], 'level': 7},
  {'name': 'Dennis Ritchie', 'options': ['Ken Thompson', 'Brian Kernighan', 'Bjarne Stroustrup', 'Linus Torvalds', 'James Gosling', 'Guido van Rossum'], 'level': 7},
  {'name': 'George Orwell', 'options': ['Leo Tolstoy', 'H. G. Wells', 'Ernest Hemingway', 'Oscar Wilde', 'Orson Welles', 'Mark Twain', 'Rudyard Kipling'], 'level': 7},
  {'name': 'Fidel Castro', 'options': ['Hugo Chávez', 'Pierre Trudeau', 'John F Kennedy', 'Miguel Díaz-Canel', 'Fulgencio Batista', 'Ramiro Valdes'], 'level': 7},
  {'name': 'Roman Abramovich', 'options': ['Oleg Deripaska', 'Alisher Usmanov', 'Mikhail Fridman', 'Ken Bates', 'Matthew Harding', 'Behdad Eghbali'], 'level': 7},
  {'name': 'Michael Phelps', 'options': ['Ian Thorpe', 'Caeleb Dressel', 'Ryan Lochte', 'Nathan Adrian', 'Adam Peaty', 'Matt Grevers'], 'level': 7},
  {'name': 'Bob Marley', 'options': ['Bob Dylan', 'Jimi Hendrix', 'Snoop Dogg', 'Jim Morrison', 'Jimmy Page', 'Chuck Berry'], 'level': 7},
  {'name': 'Silvio Berlusconi', 'options': ['Matteo Salvini', 'Andrea Giambruno', 'Giuseppe Conte ', 'Sergio Mattarella', 'Giorgio Napolitano'], 'level': 7},
  {'name': 'Olaf Scholz', 'options': ['Robert Habeck', 'Christian Lindner', 'Emmanuel Macron', 'Frank-Walter Steinmeier', 'Volodymyr Zelenskyy'], 'level': 7},
  {'name': 'Aleksander Čeferin', 'options': ['Gianni Infantino', 'Michel Platini', 'Joan Laporta', 'Ángel María Villar', 'Luis Rubiales', 'Andrea Agnelli'], 'level': 7},
  {'name': 'Ma Long', 'options': ['Fan Zhendong', 'Zhang Jike', 'Xu Xin', 'Wang Chuqin', 'Timo Boll', 'Tomokazu Harimoto', 'Ma Lin'], 'level': 7},
  {'name': 'Natalie Portman', 'options': ['Keira Knightley', 'Mila Kunis', 'Gal Gadot', 'Scarlett Johansson', 'Jennifer Lawrence', 'Winona Ryder'], 'level': 7},
  {'name': 'Lewis Capaldi', 'options': ['Ed Sheeran', 'James Arthur', 'Niall Horan', 'Dean Lewis', 'Sam Smith', 'George Ezra', 'Paolo Nutini'], 'level': 7},
  {'name': 'Shweta Gulati', 'options': ['Priya Wal', 'Shweta Tiwari', 'Neha Jhulka', 'Shefali Jariwala', 'Kanikka Kapur', 'Vidhi Pandya'], 'level': 7},
  {'name': 'Ellie Goulding', 'options': ['Rita Ora', 'Dua Lipa', 'Enya', 'Iggy Azalea', 'Meghan Trainor', 'Alexa Goddard'], 'level': 7},
  {'name': 'Garry Kasparov', 'options': ['Anatoly Karpov', 'Vladimir Kramnik', 'Bobby Fischer', 'Magnus Carlsen', 'Mikhail Tal', 'Boris Spassky'], 'level': 8},
  {'name': 'Abdul Qadeer Khan', 'options': ['Abdus Salam', 'Qasim Mehdi', 'Fazlur Rahman Khan', 'Pierre Omidyar', 'Har Gobind Khorana'], 'level': 8},
  {'name': 'Ian Thorpe', 'options': ['Ryan Lochte', 'Michael Phelps', 'Pieter van den Hoogenband', 'Grant Hackett', 'Alexander Popov', 'Kyle Chalmers'], 'level': 8},
  {'name': 'Gurinder Chadha', 'options': ['Parminder Nagra', 'Meera Syal', 'Deepa Mehta', 'Taslima Nasrin', 'Mira Nair ', 'Zoya Akhtar'], 'level': 8},
  {'name': 'Sigmund Freud', 'options': ['Charles Darwin', 'G. Stanley Hall', 'Carl Rogers', 'Carl Jung', 'Jacques Lacan'], 'level': 8},
  {'name': 'Azra Akın', 'options': ['Diana Hayden', 'Rosanna Davison', 'María Julia Mantilla', 'Taťána Kuchařová', 'Ksenia Sukhinova', 'Mireia Lalaguna', 'Stephanie Del Valle'], 'level': 8},
  {'name': 'Vanessa Hudgens', 'options': ['Ashley Tisdale', 'Ashley Benson', 'Paola Núñez', 'Olesya Rulin', 'Nikki Reed', 'Katheryn Winnick'], 'level': 8},
  {'name': 'V.S. Naipaul', 'options': ['V.S. Naipaul', 'Salman Rushdie', 'Naguib Mahfouz', 'Joseph Conrad', 'Ismail Merchant'], 'level': 8},
  {'name': 'Paul Ince', 'options': ['Bryan Robson', 'Andy Cole', 'John Barnes', 'Dwight Yorke', 'Ian Wright', 'Carlton Cole'], 'level': 8},
  {'name': 'Annie Besant', 'options': ['Sarojini Naidu', 'Aruna Asaf Ali', 'Vijaya Lakshmi Pandit', 'Sucheta Kripalani', 'Kasturba Gandhi'], 'level': 8},
  {'name': 'Vikram Sarabhai', 'options': ['Homi J. Bhabha', 'Satish Dhawan', 'Jagadish Chandra Bose', 'S. Somanath', 'Nambi Narayanan'], 'level': 8},
  {'name': 'Karnam Malleswari', 'options': ['Kunjarani Devi', 'Chanu Saikhom Mirabai', 'Mary Kom', 'Anjali Bhagwat', 'Sakshi Malik'], 'level': 8},
  {'name': 'Bradley James', 'options': ['Colin Morgan', 'Daniel Sharman', 'Chris Wood', 'Daniel Gillies', 'Paul Walker'], 'level': 8},
  {'name': 'Amartya Sen', 'options': ['Raghuram Rajan', 'Abhijit Banerjee', 'Subrahmanyan Chandrasekhar', 'Kailash Satyarthi', 'Venki Ramakrishnan', 'Har Gobind Khorana'], 'level': 8},
  {'name': 'Rosa Parks', 'options': ['Angela Davis', 'Ruby Bridges', 'Coretta Scott King', 'Claudette Colvin', 'Helen Keller'], 'level': 8},
  {'name': 'Richard Feynman', 'options': ['Niels Bohr', 'Paul Dirac', 'Werner Heisenberg', 'Enrico Fermi', 'Erwin Schrödinger', 'Louis de Broglie'], 'level': 8},
  {'name': 'Jwala Gutta', 'options': ['Ashwini Ponnappa', 'Saina Nehwal', 'Dipika Pallikal', 'Mithali Raj', 'Sakshi Malik'], 'level': 8},
  {'name': 'Aidan Turner', 'options': ['Jack Farthing', 'Luke Norris', 'Luke Evans', 'Lee Pace', 'Martin Freeman'], 'level': 8},
  {'name': 'Giorgia Meloni', 'options': ['Dina Boluarte', 'Nataša Pirc Musar', 'Borjana Krišto', 'Christine Kangaloo', 'Evika Siliņa', 'Liz Truss'], 'level': 8},
  {'name': 'Paul Blackthorne', 'options': ['David Ramsey', 'Colin Donnell', 'Stephen Amell', 'Manu Bennett', 'Rick Gonzalez'], 'level': 9},
  {'name': 'Linus Pauling', 'options': ['James Watson', 'Maurice Wilkins', 'Francis Crick', 'Erwin Schrödinger', 'Johann Purkinje'], 'level': 9},
  {'name': 'Aung San Suu Kyi', 'options': ['Khin Kyi', 'Corazon Aquino', 'Shirin Ebadi', 'Wangarĩ Muta Maathai', 'Gabriela Mistral'], 'level': 9},
  {'name': 'Haile Gebrselassie', 'options': ['Kenenisa Bekele', 'Paul Tergat', 'Mo Farah', 'Daniel Komen', 'Selemon Barega'], 'level': 9},
  {'name': 'Herbert George Wells', 'options': ['Orson Welles', 'George Orwell', 'Isaac Asimov', 'Charles Dickens', 'Arthur Conan Doyle', 'George Bernard Shaw'], 'level': 9},
  {'name': 'Lin Dan', 'options': ['Lee Chong Wei', 'Chen Long', 'Kento Momota', 'Lee Zii Jia', 'Shi Yuqi', 'Chen Jin', 'Loh Kean Yew'], 'level': 9},
  {'name': 'Lior Raz', 'options': ['Doron Ben-David', 'Itzik Cohen', 'Hisham Suliman', 'Christopher Abbott', 'Boaz Konforty'], 'level': 9},
  {'name': 'Simone Biles', 'options': ['Gabby Douglas', 'Aly Raisman', 'Jordan Chiles', 'McKayla Maroney', 'Olivia Dunne'], 'level': 9},
  {'name': 'Al Gore', 'options': ['Bill Clinton', 'George W. Bush', 'Dick Cheney', 'John Kerry', 'Jimmy Carter', 'George Stephanopoulos'], 'level': 9},
  {'name': 'Michael Bublé', 'options': ['David Foster', 'Blake Shelton', 'Bryan Adams', 'Robbie Williams', 'John Mayer'], 'level': 9},
  {'name': 'Anthony Albanese', 'options': ['John Howard', 'Kevin Rudd', 'Tony Abbott', 'Daniel Andrews', 'Scott Morrison', 'Mathias Cormann', 'Malcolm Turnbull'], 'level': 9},
  {'name': 'Roald Dahl', 'options': ['Quentin Blake', 'Tim Burton', 'David Walliams', 'Dr. Seuss', 'Lewis Carrol', 'Eric Carle'], 'level': 9},
  {'name': 'Shantanu Narayen', 'options': ['Arvind Krishna', 'Ajay Banga', 'Nikesh Arora', 'Neal Mohan', 'Sanjay Mehrotra', 'Laxman Narasimhan', 'George Kurian'], 'level': 9},
  {'name': 'René Higuita', 'options': ['Carlos Valderrama', 'Andrés Escobar', 'Faustino Asprilla', 'Freddy Rincón', 'Leonel Álvarez', 'David Ospina'], 'level': 9},
  {'name': 'Baba Amte', 'options': ['Vinoba Bhave', 'Sunderlal Bahuguna', 'Jyotirao Phule', 'Dayananda Saraswati', 'Ishwar Chandra Vidyasagar'], 'level': 9},
  {'name': 'Akira Kurosawa', 'options': ['Takashi Shimura', 'Kenji Mizoguchi', 'Masaki Kobayashi', 'Shugoro Yamamoto', 'Akira Terao'], 'level': 9},
  {'name': 'Ruskin Bond', 'options': ['Robert Frost', 'Rudyard Kipling', 'Vikram Seth', 'William Wordsworth', 'Samuel Taylor Coleridge'], 'level': 9},
  {'name': 'Paulo Coelho', 'options': ['Isaac Asimov', 'Sigmund Freud', 'Neil Gaiman', 'Stephen King', 'Frank Miller'], 'level': 10},
  {'name': 'Richard Attenborough', 'options': ['Sam Neill', 'Jeff Goldblum', 'Joseph Mazzello', 'Wayne Knight', 'Ben Kingsley', 'Bryan Forbes'], 'level': 10},
  {'name': 'Aly Raisman', 'options': ['McKayla Maroney', 'Gabby Douglas', 'Jordyn Wieber', 'Kyla Ross', 'Nastia Liukin', 'Maggie Nichols'], 'level': 10},
  {'name': 'Omar Sharif', 'options': ["Peter O'Toole", 'Ahmed Ramzy', 'Rushdy Abaza', 'Nour El-Sherif', 'Anthony Quinn'], 'level': 10},
  {'name': 'Sidney Sheldon', 'options': ['Dan Brown', 'Jeffrey Archer', 'Robert Lewis', 'John Grisham', 'Robert Ripley'], 'level': 10},
  {'name': 'Evgenia Medvedeva', 'options': ['Alina Zagitova', 'Anna Shcherbakova', 'Alexandra Trusova', 'Kamila Valieva', 'Alena Kostornaia'], 'level': 10},
  {'name': 'Luisana Lopilato', 'options': ['Camila Bordonaba', 'Florencia Peña', 'Érica Rivas', 'Lali Espósito', 'Romina Yan'], 'level': 10},
  {'name': 'Danielle Steel', 'options': ['Nora Roberts', 'Debbie Macomber', 'Linda Howard', 'Susan Kyle', 'Susan Wiggs', 'Sherryl Woods'], 'level': 10},
  {'name': 'Fu Yuanhui', 'options': ['Siobhán Haughey', 'Yang Junxuan', 'Li Bingjie', 'Cheng Yujie', 'Waka Kobori'], 'level': 10},
  {'name': 'Shirin Ebadi', 'options': ['Nasrin Sotoudeh', 'Azadeh Moaveni', 'Nazanin Boniadi', 'Mehrangiz Kar', 'Golshifteh Farahani'], 'level': 10},
  {'name': 'Roger Penrose', 'options': ['Reinhard Genzel', 'Martin Gardner', 'Christopher Isham', 'Wolfgang Rindler', 'Paul Davies'], 'level': 10},
  {'name': 'Mikaela Shiffrin', 'options': ['Lindsey Vonn', 'Petra Vlhová', 'Federica Brignone', 'Lara Gut', 'Sofia Goggia', 'Katharina Liensberger'], 'level': 10},
  {'name': 'Yelena Produnova', 'options': ['Yamilet Peña', 'Oksana Chusovitina', 'Dipa Karmakar', 'Svetlana Boginskaya', 'Tatiana Gutsu', 'Jade Carey'], 'level': 10},
  {'name': 'Antonín Panenka', 'options': ['Karol Dobiaš', 'Ivo Viktor', 'Pavel Nedvěd', 'Jan Koller', 'Ladislav Vízek'], 'level': 10},
  {'name': 'Guy Bradley', 'options': ['Jim Corbett', 'Verrier Elwin', 'Chico Mendes', 'John Muir', 'David Bellamy', 'Peter Garrett'], 'level': 10},
  {'name': 'Donald Watson', 'options': ['Tom Regan', 'Jean Genet', 'Henry Taube', 'Joaquin Phoenix', 'Geezer Butler', 'Casey Affleck'], 'level': 10},
  {'name': 'Kailash Satyarthi', 'options': ['Muhammad Yunus', 'Venki Ramakrishnan', 'Azim Premji', 'Abhijit Banerjee', 'Amartya Sen', 'Ziauddin Yousafzai'], 'level': 10},
  {'name': 'John B. Goodenough', 'options': ['M. Stanley Whittingham', 'Arumugam Manthiram', 'Clarence Zener', 'James A. Ibers', 'Harold Macmillan', 'Enrico Fermi'], 'level': 10},
  {'name': 'Liu Xiaobo', 'options': ["Wu'erkaixi", 'Wang Dan', 'Yu Jie', 'Wei Jingsheng', 'Chen Guangcheng'], 'level': 10},
  {'name': 'Akira Yoshino', 'options': ['Isamu Akasaki', 'Syukuro Manabe', 'Kenichi Fukui', 'Koichi Tanaka', 'Hideki Shirakawa', 'Tasuku Honjo'], 'level': 10},
  {'name': 'Bernard Arnault', 'options': ['Larry Ellison', 'Carlos Slim', 'François Pinault', 'Amancio Ortega', 'Steve Ballmer'], 'level': 10},
  {'name': 'Anne Frank', 'options': ['Bep Voskuijl', 'Elfriede Geiringer', 'Helen Keller', 'Eva Schloss', 'Miep Gies'], 'level': 10},
]

quiz = []

for p in people:
    p['urls'] =  fetcher.fetch('people', p['name'])
    time.sleep(1)
    quiz.append(p)

with open("output/people.json", "w") as f:
    f.write(json.dumps(quiz))
